/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FacebookTokenRequest,
  HTTPValidationError,
  MessageResponse,
  Token,
  User,
  UserConfirmSignup,
  UserRegister,
  UserRegisterAndConfirm,
} from '../models/index';
import {
    FacebookTokenRequestFromJSON,
    FacebookTokenRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    TokenFromJSON,
    TokenToJSON,
    UserFromJSON,
    UserToJSON,
    UserConfirmSignupFromJSON,
    UserConfirmSignupToJSON,
    UserRegisterFromJSON,
    UserRegisterToJSON,
    UserRegisterAndConfirmFromJSON,
    UserRegisterAndConfirmToJSON,
} from '../models/index';

export interface AdminConfirmUserApiV1AuthAdminConfirmUserPostRequest {
    requestBody: { [key: string]: any; };
}

export interface ConfirmSignupApiV1AuthConfirmSignupPostRequest {
    userConfirmSignup: UserConfirmSignup;
}

export interface ConfirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGetRequest {
    email: string;
    confirmationCode: string;
}

export interface GoogleCallbackApiV1AuthGoogleCallbackGetRequest {
    code: string;
}

export interface LoginCognitoApiV1AuthLoginAuthproviderPostRequest {
    username: string;
    password: string;
    grantType?: string | null;
    scope?: string;
    clientId?: string | null;
    clientSecret?: string | null;
}

export interface LoginCustomApiV1AuthLoginPostRequest {
    username: string;
    password: string;
    grantType?: string | null;
    scope?: string;
    clientId?: string | null;
    clientSecret?: string | null;
}

export interface RegisterAndConfirmApiV1AuthRegisterAndConfirmPostRequest {
    userRegisterAndConfirm: UserRegisterAndConfirm;
}

export interface RegisterApiV1AuthRegisterPostRequest {
    userRegister: UserRegister;
}

export interface UpdateSubscriptionIdApiV1AuthUpdateSubscriptionIdPostRequest {
    requestBody: { [key: string]: any; };
}

export interface VerifyFacebookTokenApiV1AuthFacebookVerifyTokenPostRequest {
    facebookTokenRequest: FacebookTokenRequest;
}

export interface VerifyGoogleTokenApiV1AuthGoogleVerifyTokenPostRequest {
    requestBody: { [key: string]: any; };
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Admin endpoint to confirm a user without requiring the verification code. Use this for development/testing purposes only.
     * Admin Confirm User
     */
    async adminConfirmUserApiV1AuthAdminConfirmUserPostRaw(requestParameters: AdminConfirmUserApiV1AuthAdminConfirmUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling adminConfirmUserApiV1AuthAdminConfirmUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/admin-confirm-user`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Admin endpoint to confirm a user without requiring the verification code. Use this for development/testing purposes only.
     * Admin Confirm User
     */
    async adminConfirmUserApiV1AuthAdminConfirmUserPost(requestParameters: AdminConfirmUserApiV1AuthAdminConfirmUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.adminConfirmUserApiV1AuthAdminConfirmUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Confirm user signup with the verification code sent to their email. This is required when email verification is enabled in Cognito.
     * Confirm Signup
     */
    async confirmSignupApiV1AuthConfirmSignupPostRaw(requestParameters: ConfirmSignupApiV1AuthConfirmSignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['userConfirmSignup'] == null) {
            throw new runtime.RequiredError(
                'userConfirmSignup',
                'Required parameter "userConfirmSignup" was null or undefined when calling confirmSignupApiV1AuthConfirmSignupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/confirm-signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserConfirmSignupToJSON(requestParameters['userConfirmSignup']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Confirm user signup with the verification code sent to their email. This is required when email verification is enabled in Cognito.
     * Confirm Signup
     */
    async confirmSignupApiV1AuthConfirmSignupPost(requestParameters: ConfirmSignupApiV1AuthConfirmSignupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.confirmSignupApiV1AuthConfirmSignupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Confirm user signup via email link. This endpoint is called when user clicks the confirmation link in their email.
     * Confirm Signup Link
     */
    async confirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGetRaw(requestParameters: ConfirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling confirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGet().'
            );
        }

        if (requestParameters['confirmationCode'] == null) {
            throw new runtime.RequiredError(
                'confirmationCode',
                'Required parameter "confirmationCode" was null or undefined when calling confirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/confirm-signup/{email}/{confirmation_code}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email']))).replace(`{${"confirmation_code"}}`, encodeURIComponent(String(requestParameters['confirmationCode']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Confirm user signup via email link. This endpoint is called when user clicks the confirmation link in their email.
     * Confirm Signup Link
     */
    async confirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGet(requestParameters: ConfirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.confirmSignupLinkApiV1AuthConfirmSignupEmailConfirmationCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle the OAuth callback from Cognito after Google authentication. Exchange the authorization code for Cognito tokens.
     * Google Callback
     */
    async googleCallbackApiV1AuthGoogleCallbackGetRaw(requestParameters: GoogleCallbackApiV1AuthGoogleCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling googleCallbackApiV1AuthGoogleCallbackGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/google/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handle the OAuth callback from Cognito after Google authentication. Exchange the authorization code for Cognito tokens.
     * Google Callback
     */
    async googleCallbackApiV1AuthGoogleCallbackGet(requestParameters: GoogleCallbackApiV1AuthGoogleCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.googleCallbackApiV1AuthGoogleCallbackGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Initiate Google OAuth flow via AWS Cognito. This redirects the user to Cognito\'s hosted UI which then redirects to Google. halils note: watch this video https://www.youtube.com/watch?v=GuHN_ZqHExs
     * Google Login
     */
    async googleLoginApiV1AuthGoogleLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/google/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Initiate Google OAuth flow via AWS Cognito. This redirects the user to Cognito\'s hosted UI which then redirects to Google. halils note: watch this video https://www.youtube.com/watch?v=GuHN_ZqHExs
     * Google Login
     */
    async googleLoginApiV1AuthGoogleLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.googleLoginApiV1AuthGoogleLoginGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Cognito authentication - uses AWS Cognito and returns Cognito JWT tokens. Use this endpoint when using cognito_auth_middleware.
     * Login Cognito
     */
    async loginCognitoApiV1AuthLoginAuthproviderPostRaw(requestParameters: LoginCognitoApiV1AuthLoginAuthproviderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling loginCognitoApiV1AuthLoginAuthproviderPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling loginCognitoApiV1AuthLoginAuthproviderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('client_secret', requestParameters['clientSecret'] as any);
        }

        const response = await this.request({
            path: `/api/v1/auth/login/authprovider`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Cognito authentication - uses AWS Cognito and returns Cognito JWT tokens. Use this endpoint when using cognito_auth_middleware.
     * Login Cognito
     */
    async loginCognitoApiV1AuthLoginAuthproviderPost(requestParameters: LoginCognitoApiV1AuthLoginAuthproviderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.loginCognitoApiV1AuthLoginAuthproviderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Custom JWT authentication - uses local database and custom JWT tokens. This is the default /login endpoint for backward compatibility.
     * Login Custom
     */
    async loginCustomApiV1AuthLoginPostRaw(requestParameters: LoginCustomApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling loginCustomApiV1AuthLoginPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling loginCustomApiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['grantType'] != null) {
            formParams.append('grant_type', requestParameters['grantType'] as any);
        }

        if (requestParameters['username'] != null) {
            formParams.append('username', requestParameters['username'] as any);
        }

        if (requestParameters['password'] != null) {
            formParams.append('password', requestParameters['password'] as any);
        }

        if (requestParameters['scope'] != null) {
            formParams.append('scope', requestParameters['scope'] as any);
        }

        if (requestParameters['clientId'] != null) {
            formParams.append('client_id', requestParameters['clientId'] as any);
        }

        if (requestParameters['clientSecret'] != null) {
            formParams.append('client_secret', requestParameters['clientSecret'] as any);
        }

        const response = await this.request({
            path: `/api/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Custom JWT authentication - uses local database and custom JWT tokens. This is the default /login endpoint for backward compatibility.
     * Login Custom
     */
    async loginCustomApiV1AuthLoginPost(requestParameters: LoginCustomApiV1AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.loginCustomApiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout
     */
    async logoutApiV1AuthLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Logout
     */
    async logoutApiV1AuthLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.logoutApiV1AuthLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Read Users Me
     */
    async readUsersMeApiV1AuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const response = await this.request({
            path: `/api/v1/auth/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Read Users Me
     */
    async readUsersMeApiV1AuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.readUsersMeApiV1AuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register a new user and optionally confirm immediately if confirmation code is provided.  This endpoint supports two workflows: 1. Register only: Provide email, name, password (user receives verification email) 2. Register + Confirm: Provide email, name, password, confirmation_code (immediate confirmation)  Use case: When you want to register and confirm in a single API call.
     * Register And Confirm
     */
    async registerAndConfirmApiV1AuthRegisterAndConfirmPostRaw(requestParameters: RegisterAndConfirmApiV1AuthRegisterAndConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userRegisterAndConfirm'] == null) {
            throw new runtime.RequiredError(
                'userRegisterAndConfirm',
                'Required parameter "userRegisterAndConfirm" was null or undefined when calling registerAndConfirmApiV1AuthRegisterAndConfirmPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/register-and-confirm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterAndConfirmToJSON(requestParameters['userRegisterAndConfirm']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Register a new user and optionally confirm immediately if confirmation code is provided.  This endpoint supports two workflows: 1. Register only: Provide email, name, password (user receives verification email) 2. Register + Confirm: Provide email, name, password, confirmation_code (immediate confirmation)  Use case: When you want to register and confirm in a single API call.
     * Register And Confirm
     */
    async registerAndConfirmApiV1AuthRegisterAndConfirmPost(requestParameters: RegisterAndConfirmApiV1AuthRegisterAndConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.registerAndConfirmApiV1AuthRegisterAndConfirmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new user in both AWS Cognito User Pool and local database. The user will receive a verification code via email if email verification is enabled in Cognito.
     * Register
     */
    async registerApiV1AuthRegisterPostRaw(requestParameters: RegisterApiV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userRegister'] == null) {
            throw new runtime.RequiredError(
                'userRegister',
                'Required parameter "userRegister" was null or undefined when calling registerApiV1AuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterToJSON(requestParameters['userRegister']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Register a new user in both AWS Cognito User Pool and local database. The user will receive a verification code via email if email verification is enabled in Cognito.
     * Register
     */
    async registerApiV1AuthRegisterPost(requestParameters: RegisterApiV1AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.registerApiV1AuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Subscription Id
     */
    async updateSubscriptionIdApiV1AuthUpdateSubscriptionIdPostRaw(requestParameters: UpdateSubscriptionIdApiV1AuthUpdateSubscriptionIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling updateSubscriptionIdApiV1AuthUpdateSubscriptionIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/update-subscription-id`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     * Update Subscription Id
     */
    async updateSubscriptionIdApiV1AuthUpdateSubscriptionIdPost(requestParameters: UpdateSubscriptionIdApiV1AuthUpdateSubscriptionIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.updateSubscriptionIdApiV1AuthUpdateSubscriptionIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a Facebook access token from the frontend Facebook SDK. Creates or finds the user and returns a custom JWT token for API access.  This endpoint is for when you\'re using Facebook\'s JavaScript SDK directly in your frontend.  Request body: {     \"accessToken\": \"facebook_access_token_here\",     \"userID\": \"facebook_user_id_here\" }
     * Verify Facebook Token
     */
    async verifyFacebookTokenApiV1AuthFacebookVerifyTokenPostRaw(requestParameters: VerifyFacebookTokenApiV1AuthFacebookVerifyTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['facebookTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'facebookTokenRequest',
                'Required parameter "facebookTokenRequest" was null or undefined when calling verifyFacebookTokenApiV1AuthFacebookVerifyTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/facebook/verify-token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FacebookTokenRequestToJSON(requestParameters['facebookTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Verify a Facebook access token from the frontend Facebook SDK. Creates or finds the user and returns a custom JWT token for API access.  This endpoint is for when you\'re using Facebook\'s JavaScript SDK directly in your frontend.  Request body: {     \"accessToken\": \"facebook_access_token_here\",     \"userID\": \"facebook_user_id_here\" }
     * Verify Facebook Token
     */
    async verifyFacebookTokenApiV1AuthFacebookVerifyTokenPost(requestParameters: VerifyFacebookTokenApiV1AuthFacebookVerifyTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.verifyFacebookTokenApiV1AuthFacebookVerifyTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a Google access token from the frontend Google Sign-In SDK. Creates or finds the user and returns a custom JWT token for API access.  This endpoint is for when you\'re using Google\'s JavaScript SDK directly in your frontend.  Request body: {     \"access_token\": \"google_access_token_here\" }  Note: Also supports legacy \"credential\" field for ID tokens for backward compatibility.
     * Verify Google Token
     */
    async verifyGoogleTokenApiV1AuthGoogleVerifyTokenPostRaw(requestParameters: VerifyGoogleTokenApiV1AuthGoogleVerifyTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Token>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling verifyGoogleTokenApiV1AuthGoogleVerifyTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/auth/google/verify-token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
    }

    /**
     * Verify a Google access token from the frontend Google Sign-In SDK. Creates or finds the user and returns a custom JWT token for API access.  This endpoint is for when you\'re using Google\'s JavaScript SDK directly in your frontend.  Request body: {     \"access_token\": \"google_access_token_here\" }  Note: Also supports legacy \"credential\" field for ID tokens for backward compatibility.
     * Verify Google Token
     */
    async verifyGoogleTokenApiV1AuthGoogleVerifyTokenPost(requestParameters: VerifyGoogleTokenApiV1AuthGoogleVerifyTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Token> {
        const response = await this.verifyGoogleTokenApiV1AuthGoogleVerifyTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
