/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatMessage,
  HTTPValidationError,
} from '../models/index';
import {
    ChatMessageFromJSON,
    ChatMessageToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPostRequest {
    roomId: string;
}

export interface FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost0Request {
    roomId: string;
}

export interface PostMessageApiV1ChatMessageRoomIdClientIdPostRequest {
    roomId: string;
    clientId: string;
    chatMessage: ChatMessage;
}

export interface PostMessageApiV1ChatMessageRoomIdClientIdPost0Request {
    roomId: string;
    clientId: string;
    chatMessage: ChatMessage;
}

export interface PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPostRequest {
    roomId: string;
    clientId: string;
    token: string;
    chatMessage: ChatMessage;
}

export interface PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost0Request {
    roomId: string;
    clientId: string;
    token: string;
    chatMessage: ChatMessage;
}

export interface UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPostRequest {
    chatMessage: ChatMessage;
}

export interface UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPost0Request {
    chatMessage: ChatMessage;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Handles fetching all progress messages for a specific room. Fetches all messages from Redis queue that match the roomId, similar to the print-queue command in the test script. Returns a list of ChatMessage objects.
     * Fetch All Progress Messages
     */
    async fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPostRaw(requestParameters: FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatMessage>>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/message/fetch_all_progress_messages/{roomId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatMessageFromJSON));
    }

    /**
     * Handles fetching all progress messages for a specific room. Fetches all messages from Redis queue that match the roomId, similar to the print-queue command in the test script. Returns a list of ChatMessage objects.
     * Fetch All Progress Messages
     */
    async fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost(requestParameters: FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatMessage>> {
        const response = await this.fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles fetching all progress messages for a specific room. Fetches all messages from Redis queue that match the roomId, similar to the print-queue command in the test script. Returns a list of ChatMessage objects.
     * Fetch All Progress Messages
     */
    async fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost_1Raw(requestParameters: FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChatMessage>>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/chat/message/fetch_all_progress_messages/{roomId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChatMessageFromJSON));
    }

    /**
     * Handles fetching all progress messages for a specific room. Fetches all messages from Redis queue that match the roomId, similar to the print-queue command in the test script. Returns a list of ChatMessage objects.
     * Fetch All Progress Messages
     */
    async fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost_1(requestParameters: FetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChatMessage>> {
        const response = await this.fetchAllProgressMessagesApiV1ChatMessageFetchAllProgressMessagesRoomIdPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message
     */
    async postMessageApiV1ChatMessageRoomIdClientIdPostRaw(requestParameters: PostMessageApiV1ChatMessageRoomIdClientIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost().'
            );
        }

        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/{roomId}/{clientId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))).replace(`{${"clientId"}}`, encodeURIComponent(String(requestParameters['clientId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message
     */
    async postMessageApiV1ChatMessageRoomIdClientIdPost(requestParameters: PostMessageApiV1ChatMessageRoomIdClientIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.postMessageApiV1ChatMessageRoomIdClientIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message
     */
    async postMessageApiV1ChatMessageRoomIdClientIdPost_2Raw(requestParameters: PostMessageApiV1ChatMessageRoomIdClientIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost_2().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost_2().'
            );
        }

        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling postMessageApiV1ChatMessageRoomIdClientIdPost_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/{roomId}/{clientId}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))).replace(`{${"clientId"}}`, encodeURIComponent(String(requestParameters['clientId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message
     */
    async postMessageApiV1ChatMessageRoomIdClientIdPost_2(requestParameters: PostMessageApiV1ChatMessageRoomIdClientIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.postMessageApiV1ChatMessageRoomIdClientIdPost_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message Fargate
     */
    async postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPostRaw(requestParameters: PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost().'
            );
        }

        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/frgt/{roomId}/{clientId}/{token}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))).replace(`{${"clientId"}}`, encodeURIComponent(String(requestParameters['clientId']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message Fargate
     */
    async postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost(requestParameters: PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message Fargate
     */
    async postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3Raw(requestParameters: PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3().'
            );
        }

        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3().'
            );
        }

        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/frgt/{roomId}/{clientId}/{token}`.replace(`{${"roomId"}}`, encodeURIComponent(String(requestParameters['roomId']))).replace(`{${"clientId"}}`, encodeURIComponent(String(requestParameters['clientId']))).replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles posting of a new message to the chat via REST API. The message is sent to an LLM and the reply is broadcasted back to the chat room.
     * Post Message Fargate
     */
    async postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3(requestParameters: PostMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.postMessageFargateApiV1ChatMessageFrgtRoomIdClientIdTokenPost_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles updating the video status in the database.
     * Update Video Status
     */
    async updateVideoStatusApiV1ChatMessageUpdateVideoStatusPostRaw(requestParameters: UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/update_video_status`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles updating the video status in the database.
     * Update Video Status
     */
    async updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost(requestParameters: UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateVideoStatusApiV1ChatMessageUpdateVideoStatusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles updating the video status in the database.
     * Update Video Status
     */
    async updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost_4Raw(requestParameters: UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatMessage'] == null) {
            throw new runtime.RequiredError(
                'chatMessage',
                'Required parameter "chatMessage" was null or undefined when calling updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost_4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/chat/message/update_video_status`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessageToJSON(requestParameters['chatMessage']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles updating the video status in the database.
     * Update Video Status
     */
    async updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost_4(requestParameters: UpdateVideoStatusApiV1ChatMessageUpdateVideoStatusPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateVideoStatusApiV1ChatMessageUpdateVideoStatusPost_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
