/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost,
  HTTPValidationError,
} from '../models/index';
import {
    BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostFromJSON,
    BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePostRequest {
    body: string;
}

export interface ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePost0Request {
    body: string;
}

export interface CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostRequest {
    bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost: BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost;
}

export interface CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost0Request {
    bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost: BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost;
}

/**
 * 
 */
export class SubscriptionApi extends runtime.BaseAPI {

    /**
     * Apply promotion code
     * Apply promotion code
     */
    async applyPromotionCodeApiV1SubscriptionApplyPromotionCodePostRaw(requestParameters: ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/subscription/apply-promotion-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Apply promotion code
     * Apply promotion code
     */
    async applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost(requestParameters: ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.applyPromotionCodeApiV1SubscriptionApplyPromotionCodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply promotion code
     * Apply promotion code
     */
    async applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost_1Raw(requestParameters: ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/subscription/apply-promotion-code`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Apply promotion code
     * Apply promotion code
     */
    async applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost_1(requestParameters: ApplyPromotionCodeApiV1SubscriptionApplyPromotionCodePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.applyPromotionCodeApiV1SubscriptionApplyPromotionCodePost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancel subscription
     * Cancel subscription
     */
    async cancelSubscriptionApiV1SubscriptionCancelSubscriptionPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/cancel-subscription`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Cancel subscription
     * Cancel subscription
     */
    async cancelSubscriptionApiV1SubscriptionCancelSubscriptionPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cancelSubscriptionApiV1SubscriptionCancelSubscriptionPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Cancel subscription
     * Cancel subscription
     */
    async cancelSubscriptionApiV1SubscriptionCancelSubscriptionPost_2Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/cancel-subscription`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Cancel subscription
     * Cancel subscription
     */
    async cancelSubscriptionApiV1SubscriptionCancelSubscriptionPost_2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.cancelSubscriptionApiV1SubscriptionCancelSubscriptionPost_2Raw(initOverrides);
        return await response.value();
    }

    /**
     * Create a payment intent for a given plan
     * Create payment intent
     */
    async createPaymentIntentApiV1SubscriptionCreatePaymentIntentPostRaw(requestParameters: CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost',
                'Required parameter "bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost" was null or undefined when calling createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/subscription/create-payment-intent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSON(requestParameters['bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a payment intent for a given plan
     * Create payment intent
     */
    async createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost(requestParameters: CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createPaymentIntentApiV1SubscriptionCreatePaymentIntentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a payment intent for a given plan
     * Create payment intent
     */
    async createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost_3Raw(requestParameters: CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost',
                'Required parameter "bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost" was null or undefined when calling createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/subscription/create-payment-intent`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSON(requestParameters['bodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create a payment intent for a given plan
     * Create payment intent
     */
    async createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost_3(requestParameters: CreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createPaymentIntentApiV1SubscriptionCreatePaymentIntentPost_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete account
     * Delete account
     */
    async deleteAccountApiV1SubscriptionDeleteAccountPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/delete-account`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete account
     * Delete account
     */
    async deleteAccountApiV1SubscriptionDeleteAccountPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAccountApiV1SubscriptionDeleteAccountPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete account
     * Delete account
     */
    async deleteAccountApiV1SubscriptionDeleteAccountPost_4Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/delete-account`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete account
     * Delete account
     */
    async deleteAccountApiV1SubscriptionDeleteAccountPost_4(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteAccountApiV1SubscriptionDeleteAccountPost_4Raw(initOverrides);
        return await response.value();
    }

    /**
     * Get my subscription plan
     * My subscription plan
     */
    async mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/my-subscription-plan`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get my subscription plan
     * My subscription plan
     */
    async mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get my subscription plan
     * My subscription plan
     */
    async mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPost_5Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/subscription/my-subscription-plan`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get my subscription plan
     * My subscription plan
     */
    async mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPost_5(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.mySubscriptionPlanApiV1SubscriptionMySubscriptionPlanPost_5Raw(initOverrides);
        return await response.value();
    }

}
