/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  TrimApplication,
  TrimConfigurationUI,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TrimApplicationFromJSON,
    TrimApplicationToJSON,
    TrimConfigurationUIFromJSON,
    TrimConfigurationUIToJSON,
} from '../models/index';

export interface GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPostRequest {
    videoId: string;
    trimApplication: TrimApplication;
}

export interface GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost0Request {
    videoId: string;
    trimApplication: TrimApplication;
}

export interface GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGetRequest {
    videoId: string;
}

export interface GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet0Request {
    videoId: string;
}

export interface ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGetRequest {
    index: string;
    videoId: string;
    userId: string;
}

export interface ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet0Request {
    index: string;
    videoId: string;
    userId: string;
}

/**
 * 
 */
export class UserTrimmingApi extends runtime.BaseAPI {

    /**
     * Generate shorts from a video.
     * Generate Trimming
     */
    async generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPostRaw(requestParameters: GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost().'
            );
        }

        if (requestParameters['trimApplication'] == null) {
            throw new runtime.RequiredError(
                'trimApplication',
                'Required parameter "trimApplication" was null or undefined when calling generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-trimming/generate-trimming/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrimApplicationToJSON(requestParameters['trimApplication']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Trimming
     */
    async generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost(requestParameters: GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Trimming
     */
    async generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost_1Raw(requestParameters: GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost_1().'
            );
        }

        if (requestParameters['trimApplication'] == null) {
            throw new runtime.RequiredError(
                'trimApplication',
                'Required parameter "trimApplication" was null or undefined when calling generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-trimming/generate-trimming/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrimApplicationToJSON(requestParameters['trimApplication']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Trimming
     */
    async generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost_1(requestParameters: GenerateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateTrimmingApiV1UserTrimmingGenerateTrimmingVideoIdPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Generated Trimming Info
     */
    async getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGetRaw(requestParameters: GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrimConfigurationUI>>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-trimming/generated-trimming-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrimConfigurationUIFromJSON));
    }

    /**
     * Get Generated Trimming Info
     */
    async getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet(requestParameters: GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrimConfigurationUI>> {
        const response = await this.getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Generated Trimming Info
     */
    async getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet_2Raw(requestParameters: GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrimConfigurationUI>>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-trimming/generated-trimming-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrimConfigurationUIFromJSON));
    }

    /**
     * Get Generated Trimming Info
     */
    async getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet_2(requestParameters: GetGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrimConfigurationUI>> {
        const response = await this.getGeneratedTrimmingInfoApiV1UserTrimmingGeneratedTrimmingInfoVideoIdGet_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Trimming Video File
     */
    async serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGetRaw(requestParameters: ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['index'] == null) {
            throw new runtime.RequiredError(
                'index',
                'Required parameter "index" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-trimming/serve/{user_id}/{video_id}/{index}`.replace(`{${"index"}}`, encodeURIComponent(String(requestParameters['index']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Trimming Video File
     */
    async serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet(requestParameters: ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Trimming Video File
     */
    async serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3Raw(requestParameters: ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['index'] == null) {
            throw new runtime.RequiredError(
                'index',
                'Required parameter "index" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-trimming/serve/{user_id}/{video_id}/{index}`.replace(`{${"index"}}`, encodeURIComponent(String(requestParameters['index']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Trimming Video File
     */
    async serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3(requestParameters: ServeTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.serveTrimmingVideoFileApiV1UserTrimmingServeUserIdVideoIdIndexGet_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
