/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppDbModelDocumentVideoProcessingApplication,
  HTTPValidationError,
  SchemaPaginatedUserVideoCards,
  SchemaUserVideoCard,
} from '../models/index';
import {
    AppDbModelDocumentVideoProcessingApplicationFromJSON,
    AppDbModelDocumentVideoProcessingApplicationToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SchemaPaginatedUserVideoCardsFromJSON,
    SchemaPaginatedUserVideoCardsToJSON,
    SchemaUserVideoCardFromJSON,
    SchemaUserVideoCardToJSON,
} from '../models/index';

export interface DeleteVideoApiV1UserVideosDeleteVideoVideoIdGetRequest {
    videoId: string;
}

export interface DeleteVideoApiV1UserVideosDeleteVideoVideoIdGet0Request {
    videoId: string;
}

export interface DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGetRequest {
    videoId: string;
}

export interface DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet0Request {
    videoId: string;
}

export interface DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGetRequest {
    videoId: string;
    segmentNumber: number;
}

export interface DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet0Request {
    videoId: string;
    segmentNumber: number;
}

export interface GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGetRequest {
    page?: number;
    pageSize?: number;
}

export interface GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet0Request {
    page?: number;
    pageSize?: number;
}

export interface GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGetRequest {
    application: AppDbModelDocumentVideoProcessingApplication;
}

export interface GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet0Request {
    application: AppDbModelDocumentVideoProcessingApplication;
}

export interface GetVideoInfoApiV1UserVideosVideoInfoVideoIdGetRequest {
    videoId: string;
}

export interface GetVideoInfoApiV1UserVideosVideoInfoVideoIdGet0Request {
    videoId: string;
}

export interface GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGetRequest {
    userId: string;
    videoId: string;
}

export interface GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet0Request {
    userId: string;
    videoId: string;
}

/**
 * 
 */
export class UserVideosApi extends runtime.BaseAPI {

    /**
     * Delete Video
     */
    async deleteVideoApiV1UserVideosDeleteVideoVideoIdGetRaw(requestParameters: DeleteVideoApiV1UserVideosDeleteVideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideoApiV1UserVideosDeleteVideoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/delete-video/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Video
     */
    async deleteVideoApiV1UserVideosDeleteVideoVideoIdGet(requestParameters: DeleteVideoApiV1UserVideosDeleteVideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteVideoApiV1UserVideosDeleteVideoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Video
     */
    async deleteVideoApiV1UserVideosDeleteVideoVideoIdGet_1Raw(requestParameters: DeleteVideoApiV1UserVideosDeleteVideoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideoApiV1UserVideosDeleteVideoVideoIdGet_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/delete-video/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete Video
     */
    async deleteVideoApiV1UserVideosDeleteVideoVideoIdGet_1(requestParameters: DeleteVideoApiV1UserVideosDeleteVideoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteVideoApiV1UserVideosDeleteVideoVideoIdGet_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGetRaw(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-download-original/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGetRaw(requestParameters, initOverrides);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet_2Raw(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-download-original/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet_2(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadVideoApiV1UserVideosVideoDownloadOriginalVideoIdGet_2Raw(requestParameters, initOverrides);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGetRaw(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet().'
            );
        }

        if (requestParameters['segmentNumber'] == null) {
            throw new runtime.RequiredError(
                'segmentNumber',
                'Required parameter "segmentNumber" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-download/{video_id}/{segment_number}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"segment_number"}}`, encodeURIComponent(String(requestParameters['segmentNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGetRaw(requestParameters, initOverrides);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet_3Raw(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet_3().'
            );
        }

        if (requestParameters['segmentNumber'] == null) {
            throw new runtime.RequiredError(
                'segmentNumber',
                'Required parameter "segmentNumber" was null or undefined when calling downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-download/{video_id}/{segment_number}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"segment_number"}}`, encodeURIComponent(String(requestParameters['segmentNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Download Video
     */
    async downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet_3(requestParameters: DownloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.downloadVideoApiV1UserVideosVideoDownloadVideoIdSegmentNumberGet_3Raw(requestParameters, initOverrides);
    }

    /**
     * Get Processed Videos Info
     */
    async getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGetRaw(requestParameters: GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaPaginatedUserVideoCards>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/processed-videos-info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaPaginatedUserVideoCardsFromJSON(jsonValue));
    }

    /**
     * Get Processed Videos Info
     */
    async getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet(requestParameters: GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaPaginatedUserVideoCards> {
        const response = await this.getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Processed Videos Info
     */
    async getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet_4Raw(requestParameters: GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaPaginatedUserVideoCards>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/processed-videos-info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaPaginatedUserVideoCardsFromJSON(jsonValue));
    }

    /**
     * Get Processed Videos Info
     */
    async getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet_4(requestParameters: GetProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet0Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaPaginatedUserVideoCards> {
        const response = await this.getProcessedVideosInfoApiV1UserVideosProcessedVideosInfoGet_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Processed Videos Info By Application
     */
    async getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGetRaw(requestParameters: GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SchemaUserVideoCard>>> {
        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/processed-videos-info-by-application/{application}`.replace(`{${"application"}}`, encodeURIComponent(String(requestParameters['application']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SchemaUserVideoCardFromJSON));
    }

    /**
     * Get Processed Videos Info By Application
     */
    async getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet(requestParameters: GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SchemaUserVideoCard>> {
        const response = await this.getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Processed Videos Info By Application
     */
    async getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet_5Raw(requestParameters: GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SchemaUserVideoCard>>> {
        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet_5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/processed-videos-info-by-application/{application}`.replace(`{${"application"}}`, encodeURIComponent(String(requestParameters['application']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SchemaUserVideoCardFromJSON));
    }

    /**
     * Get Processed Videos Info By Application
     */
    async getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet_5(requestParameters: GetProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SchemaUserVideoCard>> {
        const response = await this.getProcessedVideosInfoByApplicationApiV1UserVideosProcessedVideosInfoByApplicationApplicationGet_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Video Ids
     */
    async getVideoIdsApiV1UserVideosVideoIdsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video_ids`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Video Ids
     */
    async getVideoIdsApiV1UserVideosVideoIdsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getVideoIdsApiV1UserVideosVideoIdsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Video Ids
     */
    async getVideoIdsApiV1UserVideosVideoIdsGet_6Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video_ids`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Video Ids
     */
    async getVideoIdsApiV1UserVideosVideoIdsGet_6(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getVideoIdsApiV1UserVideosVideoIdsGet_6Raw(initOverrides);
        return await response.value();
    }

    /**
     * Get Video Info
     */
    async getVideoInfoApiV1UserVideosVideoInfoVideoIdGetRaw(requestParameters: GetVideoInfoApiV1UserVideosVideoInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserVideoCard>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideoInfoApiV1UserVideosVideoInfoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserVideoCardFromJSON(jsonValue));
    }

    /**
     * Get Video Info
     */
    async getVideoInfoApiV1UserVideosVideoInfoVideoIdGet(requestParameters: GetVideoInfoApiV1UserVideosVideoInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserVideoCard> {
        const response = await this.getVideoInfoApiV1UserVideosVideoInfoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Video Info
     */
    async getVideoInfoApiV1UserVideosVideoInfoVideoIdGet_7Raw(requestParameters: GetVideoInfoApiV1UserVideosVideoInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserVideoCard>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideoInfoApiV1UserVideosVideoInfoVideoIdGet_7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserVideoCardFromJSON(jsonValue));
    }

    /**
     * Get Video Info
     */
    async getVideoInfoApiV1UserVideosVideoInfoVideoIdGet_7(requestParameters: GetVideoInfoApiV1UserVideosVideoInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserVideoCard> {
        const response = await this.getVideoInfoApiV1UserVideosVideoInfoVideoIdGet_7Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Video Thumbnail
     */
    async getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGetRaw(requestParameters: GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-thumbnail/{user_id}/{video_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Video Thumbnail
     */
    async getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet(requestParameters: GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Video Thumbnail
     */
    async getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet_8Raw(requestParameters: GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet_8().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet_8().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-videos/video-thumbnail/{user_id}/{video_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Video Thumbnail
     */
    async getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet_8(requestParameters: GetVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getVideoThumbnailApiV1UserVideosVideoThumbnailUserIdVideoIdGet_8Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
