/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SchemaUserSegmentVideoList,
  ShortConfigJsonInput,
  ShortConfigJsonOutput,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SchemaUserSegmentVideoListFromJSON,
    SchemaUserSegmentVideoListToJSON,
    ShortConfigJsonInputFromJSON,
    ShortConfigJsonInputToJSON,
    ShortConfigJsonOutputFromJSON,
    ShortConfigJsonOutputToJSON,
} from '../models/index';

export interface GenerateShortsApiV1UserShortsGenerateShortsVideoIdPostRequest {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GenerateShortsApiV1UserShortsGenerateShortsVideoIdPost0Request {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePostRequest {
    shortConfigJsonInput: ShortConfigJsonInput;
}

export interface GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost0Request {
    shortConfigJsonInput: ShortConfigJsonInput;
}

export interface GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPostRequest {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost0Request {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPostRequest {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost0Request {
    videoId: string;
    requestBody: { [key: string]: any; };
}

export interface GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGetRequest {
    videoId: string;
}

export interface GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet0Request {
    videoId: string;
}

export interface ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGetRequest {
    index: string;
    videoId: string;
    userId: string;
}

export interface ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet0Request {
    index: string;
    videoId: string;
    userId: string;
}

export interface SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGetRequest {
    videoId: string;
}

export interface SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet0Request {
    videoId: string;
}

/**
 * 
 */
export class UserShortsApi extends runtime.BaseAPI {

    /**
     * Generate shorts from a video.
     * Generate Shorts
     */
    async generateShortsApiV1UserShortsGenerateShortsVideoIdPostRaw(requestParameters: GenerateShortsApiV1UserShortsGenerateShortsVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsApiV1UserShortsGenerateShortsVideoIdPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsApiV1UserShortsGenerateShortsVideoIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts
     */
    async generateShortsApiV1UserShortsGenerateShortsVideoIdPost(requestParameters: GenerateShortsApiV1UserShortsGenerateShortsVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsApiV1UserShortsGenerateShortsVideoIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts
     */
    async generateShortsApiV1UserShortsGenerateShortsVideoIdPost_1Raw(requestParameters: GenerateShortsApiV1UserShortsGenerateShortsVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsApiV1UserShortsGenerateShortsVideoIdPost_1().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsApiV1UserShortsGenerateShortsVideoIdPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts
     */
    async generateShortsApiV1UserShortsGenerateShortsVideoIdPost_1(requestParameters: GenerateShortsApiV1UserShortsGenerateShortsVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsApiV1UserShortsGenerateShortsVideoIdPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts config sample.
     * Generate Shorts Config Sample
     */
    async generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePostRaw(requestParameters: GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShortConfigJsonOutput>> {
        if (requestParameters['shortConfigJsonInput'] == null) {
            throw new runtime.RequiredError(
                'shortConfigJsonInput',
                'Required parameter "shortConfigJsonInput" was null or undefined when calling generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts/shorts-config-sample`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShortConfigJsonInputToJSON(requestParameters['shortConfigJsonInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShortConfigJsonOutputFromJSON(jsonValue));
    }

    /**
     * Generate shorts config sample.
     * Generate Shorts Config Sample
     */
    async generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost(requestParameters: GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShortConfigJsonOutput> {
        const response = await this.generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts config sample.
     * Generate Shorts Config Sample
     */
    async generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost_2Raw(requestParameters: GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShortConfigJsonOutput>> {
        if (requestParameters['shortConfigJsonInput'] == null) {
            throw new runtime.RequiredError(
                'shortConfigJsonInput',
                'Required parameter "shortConfigJsonInput" was null or undefined when calling generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts/shorts-config-sample`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShortConfigJsonInputToJSON(requestParameters['shortConfigJsonInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShortConfigJsonOutputFromJSON(jsonValue));
    }

    /**
     * Generate shorts config sample.
     * Generate Shorts Config Sample
     */
    async generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost_2(requestParameters: GenerateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShortConfigJsonOutput> {
        const response = await this.generateShortsConfigSampleApiV1UserShortsGenerateShortsShortsConfigSamplePost_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Fargate
     */
    async generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPostRaw(requestParameters: GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts-task/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Fargate
     */
    async generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost(requestParameters: GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Fargate
     */
    async generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost_3Raw(requestParameters: GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost_3().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/generate-shorts-task/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Fargate
     */
    async generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost_3(requestParameters: GenerateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsFargateApiV1UserShortsGenerateShortsTaskVideoIdPost_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Simulate
     */
    async generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPostRaw(requestParameters: GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/simulate/generate-shorts/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Simulate
     */
    async generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost(requestParameters: GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Simulate
     */
    async generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost_4Raw(requestParameters: GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost_4().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost_4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user-shorts/simulate/generate-shorts/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Generate shorts from a video.
     * Generate Shorts Simulate
     */
    async generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost_4(requestParameters: GenerateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.generateShortsSimulateApiV1UserShortsSimulateGenerateShortsVideoIdPost_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Generated Shorts Info
     */
    async getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGetRaw(requestParameters: GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserSegmentVideoList>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/generated-shorts-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserSegmentVideoListFromJSON(jsonValue));
    }

    /**
     * Get Generated Shorts Info
     */
    async getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet(requestParameters: GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserSegmentVideoList> {
        const response = await this.getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Generated Shorts Info
     */
    async getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet_5Raw(requestParameters: GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserSegmentVideoList>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet_5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/generated-shorts-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserSegmentVideoListFromJSON(jsonValue));
    }

    /**
     * Get Generated Shorts Info
     */
    async getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet_5(requestParameters: GetGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserSegmentVideoList> {
        const response = await this.getGeneratedShortsInfoApiV1UserShortsGeneratedShortsInfoVideoIdGet_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Short Video File
     */
    async serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGetRaw(requestParameters: ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['index'] == null) {
            throw new runtime.RequiredError(
                'index',
                'Required parameter "index" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/serve/{user_id}/{video_id}/{index}`.replace(`{${"index"}}`, encodeURIComponent(String(requestParameters['index']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Short Video File
     */
    async serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet(requestParameters: ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Short Video File
     */
    async serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6Raw(requestParameters: ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['index'] == null) {
            throw new runtime.RequiredError(
                'index',
                'Required parameter "index" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/serve/{user_id}/{video_id}/{index}`.replace(`{${"index"}}`, encodeURIComponent(String(requestParameters['index']))).replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Serves a video file for video player consumption. Supports proper MIME types, range requests, and file streaming for video playback.
     * Serve Short Video File
     */
    async serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6(requestParameters: ServeShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.serveShortVideoFileApiV1UserShortsServeUserIdVideoIdIndexGet_6Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simulate Get Generated Shorts Info
     */
    async simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGetRaw(requestParameters: SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserSegmentVideoList>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/simulate/generated-shorts-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserSegmentVideoListFromJSON(jsonValue));
    }

    /**
     * Simulate Get Generated Shorts Info
     */
    async simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet(requestParameters: SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserSegmentVideoList> {
        const response = await this.simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Simulate Get Generated Shorts Info
     */
    async simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet_7Raw(requestParameters: SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaUserSegmentVideoList>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet_7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user-shorts/simulate/generated-shorts-info/{video_id}`.replace(`{${"video_id"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaUserSegmentVideoListFromJSON(jsonValue));
    }

    /**
     * Simulate Get Generated Shorts Info
     */
    async simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet_7(requestParameters: SimulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaUserSegmentVideoList> {
        const response = await this.simulateGetGeneratedShortsInfoApiV1UserShortsSimulateGeneratedShortsInfoVideoIdGet_7Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
