/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckUserAllowanceForUploadResponse,
  HTTPValidationError,
} from '../models/index';
import {
    CheckUserAllowanceForUploadResponseFromJSON,
    CheckUserAllowanceForUploadResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetStatusApiV1VideouploadStatusUserVideoIdGetRequest {
    userVideoId: string;
}

export interface GetStatusApiV1VideouploadStatusUserVideoIdGet0Request {
    userVideoId: string;
}

export interface UploadVideoApiV1VideouploadUploadPostRequest {
    file: Blob;
}

export interface UploadVideoApiV1VideouploadUploadPost0Request {
    file: Blob;
}

/**
 * 
 */
export class VideoUploadApi extends runtime.BaseAPI {

    /**
     * Check User Allowance For Uplaod
     */
    async checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckUserAllowanceForUploadResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/videoupload/check-user-allowance-for-upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckUserAllowanceForUploadResponseFromJSON(jsonValue));
    }

    /**
     * Check User Allowance For Uplaod
     */
    async checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckUserAllowanceForUploadResponse> {
        const response = await this.checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Check User Allowance For Uplaod
     */
    async checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPost_1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckUserAllowanceForUploadResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/videoupload/check-user-allowance-for-upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckUserAllowanceForUploadResponseFromJSON(jsonValue));
    }

    /**
     * Check User Allowance For Uplaod
     */
    async checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPost_1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckUserAllowanceForUploadResponse> {
        const response = await this.checkUserAllowanceForUplaodApiV1VideouploadCheckUserAllowanceForUploadPost_1Raw(initOverrides);
        return await response.value();
    }

    /**
     * Get shorts from a video.
     * Get Status
     */
    async getStatusApiV1VideouploadStatusUserVideoIdGetRaw(requestParameters: GetStatusApiV1VideouploadStatusUserVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userVideoId'] == null) {
            throw new runtime.RequiredError(
                'userVideoId',
                'Required parameter "userVideoId" was null or undefined when calling getStatusApiV1VideouploadStatusUserVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/videoupload/status/{user_video_id}`.replace(`{${"user_video_id"}}`, encodeURIComponent(String(requestParameters['userVideoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get shorts from a video.
     * Get Status
     */
    async getStatusApiV1VideouploadStatusUserVideoIdGet(requestParameters: GetStatusApiV1VideouploadStatusUserVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getStatusApiV1VideouploadStatusUserVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get shorts from a video.
     * Get Status
     */
    async getStatusApiV1VideouploadStatusUserVideoIdGet_2Raw(requestParameters: GetStatusApiV1VideouploadStatusUserVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userVideoId'] == null) {
            throw new runtime.RequiredError(
                'userVideoId',
                'Required parameter "userVideoId" was null or undefined when calling getStatusApiV1VideouploadStatusUserVideoIdGet_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/videoupload/status/{user_video_id}`.replace(`{${"user_video_id"}}`, encodeURIComponent(String(requestParameters['userVideoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get shorts from a video.
     * Get Status
     */
    async getStatusApiV1VideouploadStatusUserVideoIdGet_2(requestParameters: GetStatusApiV1VideouploadStatusUserVideoIdGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getStatusApiV1VideouploadStatusUserVideoIdGet_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles uploading of large video files (60-100MB). Saves the file and then triggers video processing.
     * Upload Video
     */
    async uploadVideoApiV1VideouploadUploadPostRaw(requestParameters: UploadVideoApiV1VideouploadUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVideoApiV1VideouploadUploadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/videoupload/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles uploading of large video files (60-100MB). Saves the file and then triggers video processing.
     * Upload Video
     */
    async uploadVideoApiV1VideouploadUploadPost(requestParameters: UploadVideoApiV1VideouploadUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadVideoApiV1VideouploadUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handles uploading of large video files (60-100MB). Saves the file and then triggers video processing.
     * Upload Video
     */
    async uploadVideoApiV1VideouploadUploadPost_3Raw(requestParameters: UploadVideoApiV1VideouploadUploadPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadVideoApiV1VideouploadUploadPost_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/videoupload/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handles uploading of large video files (60-100MB). Saves the file and then triggers video processing.
     * Upload Video
     */
    async uploadVideoApiV1VideouploadUploadPost_3(requestParameters: UploadVideoApiV1VideouploadUploadPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadVideoApiV1VideouploadUploadPost_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
