#!/usr/bin/env python3
# flake8: noqa: E501
"""
Script to calculate total AI costs from ai_cost_total.json files.

Usage:
    python scripts/calculate_ai_costs.py <path_to_ai_cost_total.json>
    
Example:
    python scripts/calculate_ai_costs.py app/klippers_warehouse/user123/video456/ai_cost_total.json
"""

import json
import sys
from collections import defaultdict
from pathlib import Path


def calculate_costs(json_file_path):
    """
    Calculates total and breakdown of AI costs from ai_cost_total.json file.
    
    Args:
        json_file_path: Path to the ai_cost_total.json file
    """
    try:
        with open(json_file_path, 'r') as f:
            cost_data = json.load(f)
    except FileNotFoundError:
        print(f"Error: File not found: {json_file_path}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in file: {e}")
        sys.exit(1)
    
    # Expect the new format (dict with total_cost and ai_cost_items)
    if isinstance(cost_data, dict) and 'ai_cost_items' in cost_data:
        total_cost = float(cost_data.get('total_cost', 0.0))
        cost_items = cost_data['ai_cost_items']
    else:
        print("Error: Invalid format. Expected dict with 'total_cost' and 'ai_cost_items'")
        print("Note: This script expects ai_cost_total.json generated by the calculate-total command")
        sys.exit(1)
    
    # Calculate breakdowns
    costs_by_provider = defaultdict(float)
    costs_by_operation = defaultdict(float)
    costs_by_model = defaultdict(float)
    operation_counts = defaultdict(int)
    
    for entry in cost_items:
        cost = float(entry.get('cost', 0))
        provider = entry.get('provider', 'unknown')
        operation = entry.get('operation_name', 'unknown')
        model = entry.get('model', 'unknown')
        
        costs_by_provider[provider] += cost
        costs_by_operation[operation] += cost
        costs_by_model[model] += cost
        operation_counts[operation] += 1
    
    # Print results
    print("=" * 80)
    print(f"AI COST ANALYSIS: {Path(json_file_path).name}")
    print("=" * 80)
    print()
    
    print(f"📊 TOTAL COST: ${total_cost:.6f}")
    print(f"📝 Total Operations: {len(cost_items)}")
    print()
    
    print("-" * 80)
    print("💰 COSTS BY PROVIDER:")
    print("-" * 80)
    for provider, cost in sorted(costs_by_provider.items(), key=lambda x: x[1], reverse=True):
        percentage = (cost / total_cost * 100) if total_cost > 0 else 0
        print(f"  {provider:30s} ${cost:10.6f} ({percentage:5.2f}%)")
    print()
    
    print("-" * 80)
    print("🔧 COSTS BY OPERATION:")
    print("-" * 80)
    for operation, cost in sorted(costs_by_operation.items(), key=lambda x: x[1], reverse=True):
        count = operation_counts[operation]
        percentage = (cost / total_cost * 100) if total_cost > 0 else 0
        avg_cost = cost / count if count > 0 else 0
        print(f"  {operation:35s} ${cost:10.6f} ({percentage:5.2f}%) [{count:4d} ops, avg: ${avg_cost:.6f}]")
    print()
    
    print("-" * 80)
    print("🤖 COSTS BY MODEL:")
    print("-" * 80)
    for model, cost in sorted(costs_by_model.items(), key=lambda x: x[1], reverse=True):
        percentage = (cost / total_cost * 100) if total_cost > 0 else 0
        print(f"  {model:40s} ${cost:10.6f} ({percentage:5.2f}%)")
    print()
    
    print("=" * 80)
    
    return {
        'total_cost': total_cost,
        'total_operations': len(cost_items),
        'by_provider': dict(costs_by_provider),
        'by_operation': dict(costs_by_operation),
        'by_model': dict(costs_by_model)
    }


def main():
    if len(sys.argv) < 2:
        print("Usage: python calculate_ai_costs.py <path_to_ai_cost_total.json>")
        print()
        print("Example:")
        print("  python scripts/calculate_ai_costs.py app/klippers_warehouse/user123/video456/ai_cost_total.json")
        sys.exit(1)
    
    json_file_path = sys.argv[1]
    calculate_costs(json_file_path)


if __name__ == '__main__':
    main()

