/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication = {
    GenerateShorts: 'GENERATE_SHORTS',
    GenerateSubtitling: 'GENERATE_SUBTITLING',
    ApplyTrim: 'APPLY_TRIM',
    ApplyVoiceOver: 'APPLY_VOICE_OVER',
    ApplyVlog: 'APPLY_VLOG',
    ApplyPodcastTemplate: 'APPLY_PODCAST_TEMPLATE'
} as const;
export type AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication = typeof AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication[keyof typeof AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication];


export function instanceOfAppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication(value: any): boolean {
    for (const key in AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication) {
        if (Object.prototype.hasOwnProperty.call(AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication, key)) {
            if (AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication[key as keyof typeof AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSON(json: any): AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSONTyped(json, false);
}

export function AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return json as AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication;
}

export function AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSON(value?: AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication | null): any {
    return value as any;
}

export function AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSONTyped(value: any, ignoreDiscriminator: boolean): AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return value as AppKlipperscmdClippercmdModelShortConfigModelVideoProcessingApplication;
}

