/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication = {
    GenerateShorts: 'GENERATE_SHORTS',
    GenerateSubtitling: 'GENERATE_SUBTITLING',
    ApplyTrim: 'APPLY_TRIM',
    ApplyVoiceOver: 'APPLY_VOICE_OVER',
    ApplyVlog: 'APPLY_VLOG',
    ApplyPodcastTemplate: 'APPLY_PODCAST_TEMPLATE'
} as const;
export type AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication = typeof AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication[keyof typeof AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication];


export function instanceOfAppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication(value: any): boolean {
    for (const key in AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication) {
        if (Object.prototype.hasOwnProperty.call(AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication, key)) {
            if (AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication[key as keyof typeof AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSON(json: any): AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSONTyped(json, false);
}

export function AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return json as AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication;
}

export function AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSON(value?: AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication | null): any {
    return value as any;
}

export function AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSONTyped(value: any, ignoreDiscriminator: boolean): AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication {
    return value as AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication;
}

