/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost
 */
export interface BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost {
    /**
     * 
     * @type {string}
     * @memberof BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost
     */
    name: string;
}

/**
 * Check if a given object implements the BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost interface.
 */
export function instanceOfBodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost(value: object): value is BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost {
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostFromJSON(json: any): BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost {
    return BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostFromJSONTyped(json, false);
}

export function BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost {
    if (json == null) {
        return json;
    }
    return {
        
        'planId': json['planId'],
        'email': json['email'],
        'name': json['name'],
    };
}

export function BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSON(json: any): BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost {
    return BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSONTyped(json, false);
}

export function BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPostToJSONTyped(value?: BodyCreatePaymentIntentApiV1SubscriptionCreatePaymentIntentPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planId': value['planId'],
        'email': value['email'],
        'name': value['name'],
    };
}

