/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BoxRel
 */
export interface BoxRel {
    /**
     * 
     * @type {number}
     * @memberof BoxRel
     */
    left: number;
    /**
     * 
     * @type {number}
     * @memberof BoxRel
     */
    top: number;
    /**
     * 
     * @type {number}
     * @memberof BoxRel
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof BoxRel
     */
    height: number;
}

/**
 * Check if a given object implements the BoxRel interface.
 */
export function instanceOfBoxRel(value: object): value is BoxRel {
    if (!('left' in value) || value['left'] === undefined) return false;
    if (!('top' in value) || value['top'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function BoxRelFromJSON(json: any): BoxRel {
    return BoxRelFromJSONTyped(json, false);
}

export function BoxRelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoxRel {
    if (json == null) {
        return json;
    }
    return {
        
        'left': json['Left'],
        'top': json['Top'],
        'width': json['Width'],
        'height': json['Height'],
    };
}

export function BoxRelToJSON(json: any): BoxRel {
    return BoxRelToJSONTyped(json, false);
}

export function BoxRelToJSONTyped(value?: BoxRel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Left': value['left'],
        'Top': value['top'],
        'Width': value['width'],
        'Height': value['height'],
    };
}

