/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    timestamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    roomId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessage
     */
    isTesting?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    companyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    machineId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    lineId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    conversationId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChatMessage
     */
    chunkIds?: Array<string> | null;
}

/**
 * Check if a given object implements the ChatMessage interface.
 */
export function instanceOfChatMessage(value: object): value is ChatMessage {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    return true;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
    return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'message': json['message'],
        'clientId': json['clientId'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'roomId': json['roomId'],
        'isTesting': json['isTesting'] == null ? undefined : json['isTesting'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'machineId': json['machineId'] == null ? undefined : json['machineId'],
        'lineId': json['lineId'] == null ? undefined : json['lineId'],
        'conversationId': json['conversationId'] == null ? undefined : json['conversationId'],
        'chunkIds': json['chunkIds'] == null ? undefined : json['chunkIds'],
    };
}

export function ChatMessageToJSON(json: any): ChatMessage {
    return ChatMessageToJSONTyped(json, false);
}

export function ChatMessageToJSONTyped(value?: ChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'message': value['message'],
        'clientId': value['clientId'],
        'timestamp': value['timestamp'],
        'roomId': value['roomId'],
        'isTesting': value['isTesting'],
        'companyId': value['companyId'],
        'machineId': value['machineId'],
        'lineId': value['lineId'],
        'conversationId': value['conversationId'],
        'chunkIds': value['chunkIds'],
    };
}

