/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedAt
 */
export interface CreatedAt {
}

/**
 * Check if a given object implements the CreatedAt interface.
 */
export function instanceOfCreatedAt(value: object): value is CreatedAt {
    return true;
}

export function CreatedAtFromJSON(json: any): CreatedAt {
    return CreatedAtFromJSONTyped(json, false);
}

export function CreatedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedAt {
    return json;
}

export function CreatedAtToJSON(json: any): CreatedAt {
    return CreatedAtToJSONTyped(json, false);
}

export function CreatedAtToJSONTyped(value?: CreatedAt | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

