/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CroppingOperator = {
    Ai: 'AI',
    Manual: 'MANUAL',
    Custom: 'CUSTOM'
} as const;
export type CroppingOperator = typeof CroppingOperator[keyof typeof CroppingOperator];


export function instanceOfCroppingOperator(value: any): boolean {
    for (const key in CroppingOperator) {
        if (Object.prototype.hasOwnProperty.call(CroppingOperator, key)) {
            if (CroppingOperator[key as keyof typeof CroppingOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CroppingOperatorFromJSON(json: any): CroppingOperator {
    return CroppingOperatorFromJSONTyped(json, false);
}

export function CroppingOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CroppingOperator {
    return json as CroppingOperator;
}

export function CroppingOperatorToJSON(value?: CroppingOperator | null): any {
    return value as any;
}

export function CroppingOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): CroppingOperator {
    return value as CroppingOperator;
}

