/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocialMediaPlatform } from './SocialMediaPlatform';
import {
    SocialMediaPlatformFromJSON,
    SocialMediaPlatformFromJSONTyped,
    SocialMediaPlatformToJSON,
    SocialMediaPlatformToJSONTyped,
} from './SocialMediaPlatform';

/**
 * 
 * @export
 * @interface DissaminateOnSocialMediaPlatforms
 */
export interface DissaminateOnSocialMediaPlatforms {
}

/**
 * Check if a given object implements the DissaminateOnSocialMediaPlatforms interface.
 */
export function instanceOfDissaminateOnSocialMediaPlatforms(value: object): value is DissaminateOnSocialMediaPlatforms {
    return true;
}

export function DissaminateOnSocialMediaPlatformsFromJSON(json: any): DissaminateOnSocialMediaPlatforms {
    return DissaminateOnSocialMediaPlatformsFromJSONTyped(json, false);
}

export function DissaminateOnSocialMediaPlatformsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DissaminateOnSocialMediaPlatforms {
    return json;
}

export function DissaminateOnSocialMediaPlatformsToJSON(json: any): DissaminateOnSocialMediaPlatforms {
    return DissaminateOnSocialMediaPlatformsToJSONTyped(json, false);
}

export function DissaminateOnSocialMediaPlatformsToJSONTyped(value?: DissaminateOnSocialMediaPlatforms | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

