/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FaceFinalPosition } from './FaceFinalPosition';
import {
    FaceFinalPositionFromJSON,
    FaceFinalPositionFromJSONTyped,
    FaceFinalPositionToJSON,
    FaceFinalPositionToJSONTyped,
} from './FaceFinalPosition';
import type { BoxRel } from './BoxRel';
import {
    BoxRelFromJSON,
    BoxRelFromJSONTyped,
    BoxRelToJSON,
    BoxRelToJSONTyped,
} from './BoxRel';

/**
 * 
 * @export
 * @interface FaceCropping
 */
export interface FaceCropping {
    /**
     * 
     * @type {BoxRel}
     * @memberof FaceCropping
     */
    croppingBbox?: BoxRel | null;
    /**
     * 
     * @type {FaceFinalPosition}
     * @memberof FaceCropping
     */
    finalPosition?: FaceFinalPosition | null;
    /**
     * 
     * @type {number}
     * @memberof FaceCropping
     */
    faceIndex: number;
}



/**
 * Check if a given object implements the FaceCropping interface.
 */
export function instanceOfFaceCropping(value: object): value is FaceCropping {
    if (!('faceIndex' in value) || value['faceIndex'] === undefined) return false;
    return true;
}

export function FaceCroppingFromJSON(json: any): FaceCropping {
    return FaceCroppingFromJSONTyped(json, false);
}

export function FaceCroppingFromJSONTyped(json: any, ignoreDiscriminator: boolean): FaceCropping {
    if (json == null) {
        return json;
    }
    return {
        
        'croppingBbox': json['cropping_bbox'] == null ? undefined : BoxRelFromJSON(json['cropping_bbox']),
        'finalPosition': json['final_position'] == null ? undefined : FaceFinalPositionFromJSON(json['final_position']),
        'faceIndex': json['face_index'],
    };
}

export function FaceCroppingToJSON(json: any): FaceCropping {
    return FaceCroppingToJSONTyped(json, false);
}

export function FaceCroppingToJSONTyped(value?: FaceCropping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cropping_bbox': BoxRelToJSON(value['croppingBbox']),
        'final_position': FaceFinalPositionToJSON(value['finalPosition']),
        'face_index': value['faceIndex'],
    };
}

