/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FaceFinalPosition = {
    TopOfTwo: 'top_of_two',
    BottomOfTwo: 'bottom_of_two',
    FullScreen: 'full_screen',
    LeftOfTwo: 'left_of_two',
    RightOfTwo: 'right_of_two',
    TopOfThree: 'top_of_three',
    BottomOfThree: 'bottom_of_three',
    VerticalMiddleOfThree: 'vertical_middle_of_three',
    TopOfThree2: 'top_of_three',
    BottomOfThree2: 'bottom_of_three',
    HorizontalMiddleOfThree: 'horizontal_middle_of_three',
    LeftTopOfFour: 'left_top_of_four',
    RightTopOfFour: 'right_top_of_four',
    LeftBottomOfFour: 'left_bottom_of_four',
    RightBottomOfFour: 'right_bottom_of_four'
} as const;
export type FaceFinalPosition = typeof FaceFinalPosition[keyof typeof FaceFinalPosition];


export function instanceOfFaceFinalPosition(value: any): boolean {
    for (const key in FaceFinalPosition) {
        if (Object.prototype.hasOwnProperty.call(FaceFinalPosition, key)) {
            if (FaceFinalPosition[key as keyof typeof FaceFinalPosition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FaceFinalPositionFromJSON(json: any): FaceFinalPosition {
    return FaceFinalPositionFromJSONTyped(json, false);
}

export function FaceFinalPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FaceFinalPosition {
    return json as FaceFinalPosition;
}

export function FaceFinalPositionToJSON(value?: FaceFinalPosition | null): any {
    return value as any;
}

export function FaceFinalPositionToJSONTyped(value: any, ignoreDiscriminator: boolean): FaceFinalPosition {
    return value as FaceFinalPosition;
}

