/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacebookTokenRequest
 */
export interface FacebookTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof FacebookTokenRequest
     */
    accessToken: string;
}

/**
 * Check if a given object implements the FacebookTokenRequest interface.
 */
export function instanceOfFacebookTokenRequest(value: object): value is FacebookTokenRequest {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function FacebookTokenRequestFromJSON(json: any): FacebookTokenRequest {
    return FacebookTokenRequestFromJSONTyped(json, false);
}

export function FacebookTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacebookTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function FacebookTokenRequestToJSON(json: any): FacebookTokenRequest {
    return FacebookTokenRequestToJSONTyped(json, false);
}

export function FacebookTokenRequestToJSONTyped(value?: FacebookTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

