/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FaceCropping } from './FaceCropping';
import {
    FaceCroppingFromJSON,
    FaceCroppingFromJSONTyped,
    FaceCroppingToJSON,
    FaceCroppingToJSONTyped,
} from './FaceCropping';

/**
 * 
 * @export
 * @interface ManualCropping
 */
export interface ManualCropping {
    /**
     * 
     * @type {string}
     * @memberof ManualCropping
     */
    localFaceDirectoryName?: string | null;
    /**
     * 
     * @type {Array<FaceCropping>}
     * @memberof ManualCropping
     */
    faceCropping?: Array<FaceCropping> | null;
}

/**
 * Check if a given object implements the ManualCropping interface.
 */
export function instanceOfManualCropping(value: object): value is ManualCropping {
    return true;
}

export function ManualCroppingFromJSON(json: any): ManualCropping {
    return ManualCroppingFromJSONTyped(json, false);
}

export function ManualCroppingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualCropping {
    if (json == null) {
        return json;
    }
    return {
        
        'localFaceDirectoryName': json['local_face_directory_name'] == null ? undefined : json['local_face_directory_name'],
        'faceCropping': json['face_cropping'] == null ? undefined : ((json['face_cropping'] as Array<any>).map(FaceCroppingFromJSON)),
    };
}

export function ManualCroppingToJSON(json: any): ManualCropping {
    return ManualCroppingToJSONTyped(json, false);
}

export function ManualCroppingToJSONTyped(value?: ManualCropping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'local_face_directory_name': value['localFaceDirectoryName'],
        'face_cropping': value['faceCropping'] == null ? undefined : ((value['faceCropping'] as Array<any>).map(FaceCroppingToJSON)),
    };
}

