/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResolutionMode = {
    _8k: '8k',
    _4k: '4k',
    FullHd: 'full_hd',
    Hd: 'hd',
    Hd720p: 'hd_720p',
    Sd480p: 'sd_480p',
    Sd360p: 'sd_360p',
    Sd240p: 'sd_240p',
    Sd180p: 'sd_180p',
    Sd144p: 'sd_144p',
    Sd120p: 'sd_120p',
    Sd108p: 'sd_108p',
    Sd96p: 'sd_96p'
} as const;
export type ResolutionMode = typeof ResolutionMode[keyof typeof ResolutionMode];


export function instanceOfResolutionMode(value: any): boolean {
    for (const key in ResolutionMode) {
        if (Object.prototype.hasOwnProperty.call(ResolutionMode, key)) {
            if (ResolutionMode[key as keyof typeof ResolutionMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResolutionModeFromJSON(json: any): ResolutionMode {
    return ResolutionModeFromJSONTyped(json, false);
}

export function ResolutionModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolutionMode {
    return json as ResolutionMode;
}

export function ResolutionModeToJSON(value?: ResolutionMode | null): any {
    return value as any;
}

export function ResolutionModeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResolutionMode {
    return value as ResolutionMode;
}

