/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaUserVideoCard } from './SchemaUserVideoCard';
import {
    SchemaUserVideoCardFromJSON,
    SchemaUserVideoCardFromJSONTyped,
    SchemaUserVideoCardToJSON,
    SchemaUserVideoCardToJSONTyped,
} from './SchemaUserVideoCard';

/**
 * 
 * @export
 * @interface SchemaPaginatedUserVideoCards
 */
export interface SchemaPaginatedUserVideoCards {
    /**
     * 
     * @type {Array<SchemaUserVideoCard>}
     * @memberof SchemaPaginatedUserVideoCards
     */
    items: Array<SchemaUserVideoCard>;
    /**
     * 
     * @type {number}
     * @memberof SchemaPaginatedUserVideoCards
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaPaginatedUserVideoCards
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaPaginatedUserVideoCards
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof SchemaPaginatedUserVideoCards
     */
    totalPages: number;
}

/**
 * Check if a given object implements the SchemaPaginatedUserVideoCards interface.
 */
export function instanceOfSchemaPaginatedUserVideoCards(value: object): value is SchemaPaginatedUserVideoCards {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function SchemaPaginatedUserVideoCardsFromJSON(json: any): SchemaPaginatedUserVideoCards {
    return SchemaPaginatedUserVideoCardsFromJSONTyped(json, false);
}

export function SchemaPaginatedUserVideoCardsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaPaginatedUserVideoCards {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SchemaUserVideoCardFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['page_size'],
        'totalPages': json['total_pages'],
    };
}

export function SchemaPaginatedUserVideoCardsToJSON(json: any): SchemaPaginatedUserVideoCards {
    return SchemaPaginatedUserVideoCardsToJSONTyped(json, false);
}

export function SchemaPaginatedUserVideoCardsToJSONTyped(value?: SchemaPaginatedUserVideoCards | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SchemaUserVideoCardToJSON)),
        'total': value['total'],
        'page': value['page'],
        'page_size': value['pageSize'],
        'total_pages': value['totalPages'],
    };
}

