/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaUserVideoDetails
 */
export interface SchemaUserVideoDetails {
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoDetails
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoDetails
     */
    end: string;
    /**
     * 
     * @type {number}
     * @memberof SchemaUserVideoDetails
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoDetails
     */
    why: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoDetails
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaUserVideoDetails
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the SchemaUserVideoDetails interface.
 */
export function instanceOfSchemaUserVideoDetails(value: object): value is SchemaUserVideoDetails {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('why' in value) || value['why'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function SchemaUserVideoDetailsFromJSON(json: any): SchemaUserVideoDetails {
    return SchemaUserVideoDetailsFromJSONTyped(json, false);
}

export function SchemaUserVideoDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaUserVideoDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
        'score': json['score'],
        'why': json['why'],
        'title': json['title'],
        'tags': json['tags'],
    };
}

export function SchemaUserVideoDetailsToJSON(json: any): SchemaUserVideoDetails {
    return SchemaUserVideoDetailsToJSONTyped(json, false);
}

export function SchemaUserVideoDetailsToJSONTyped(value?: SchemaUserVideoDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
        'score': value['score'],
        'why': value['why'],
        'title': value['title'],
        'tags': value['tags'],
    };
}

