/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppDbModelDocumentVideoProcessingApplication } from './AppDbModelDocumentVideoProcessingApplication';
import {
    AppDbModelDocumentVideoProcessingApplicationFromJSON,
    AppDbModelDocumentVideoProcessingApplicationFromJSONTyped,
    AppDbModelDocumentVideoProcessingApplicationToJSON,
    AppDbModelDocumentVideoProcessingApplicationToJSONTyped,
} from './AppDbModelDocumentVideoProcessingApplication';
import type { VideoAspectRatio } from './VideoAspectRatio';
import {
    VideoAspectRatioFromJSON,
    VideoAspectRatioFromJSONTyped,
    VideoAspectRatioToJSON,
    VideoAspectRatioToJSONTyped,
} from './VideoAspectRatio';
import type { CreatedAt } from './CreatedAt';
import {
    CreatedAtFromJSON,
    CreatedAtFromJSONTyped,
    CreatedAtToJSON,
    CreatedAtToJSONTyped,
} from './CreatedAt';
import type { UpdatedAt } from './UpdatedAt';
import {
    UpdatedAtFromJSON,
    UpdatedAtFromJSONTyped,
    UpdatedAtToJSON,
    UpdatedAtToJSONTyped,
} from './UpdatedAt';

/**
 * 
 * @export
 * @interface SchemaUserVideoCard
 */
export interface SchemaUserVideoCard {
    /**
     * 
     * @type {number}
     * @memberof SchemaUserVideoCard
     */
    videoDuration: number;
    /**
     * 
     * @type {VideoAspectRatio}
     * @memberof SchemaUserVideoCard
     */
    videoAspectRatio: VideoAspectRatio;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoCard
     */
    videoTitle: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoCard
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoCard
     */
    videoThumbnailUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoCard
     */
    videoUrl: string;
    /**
     * 
     * @type {CreatedAt}
     * @memberof SchemaUserVideoCard
     */
    createdAt: CreatedAt;
    /**
     * 
     * @type {UpdatedAt}
     * @memberof SchemaUserVideoCard
     */
    updatedAt: UpdatedAt;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserVideoCard
     */
    status: string;
    /**
     * 
     * @type {AppDbModelDocumentVideoProcessingApplication}
     * @memberof SchemaUserVideoCard
     */
    appliedApplication?: AppDbModelDocumentVideoProcessingApplication;
}



/**
 * Check if a given object implements the SchemaUserVideoCard interface.
 */
export function instanceOfSchemaUserVideoCard(value: object): value is SchemaUserVideoCard {
    if (!('videoDuration' in value) || value['videoDuration'] === undefined) return false;
    if (!('videoAspectRatio' in value) || value['videoAspectRatio'] === undefined) return false;
    if (!('videoTitle' in value) || value['videoTitle'] === undefined) return false;
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('videoThumbnailUrl' in value) || value['videoThumbnailUrl'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SchemaUserVideoCardFromJSON(json: any): SchemaUserVideoCard {
    return SchemaUserVideoCardFromJSONTyped(json, false);
}

export function SchemaUserVideoCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaUserVideoCard {
    if (json == null) {
        return json;
    }
    return {
        
        'videoDuration': json['video_duration'],
        'videoAspectRatio': VideoAspectRatioFromJSON(json['video_aspect_ratio']),
        'videoTitle': json['video_title'],
        'videoId': json['video_id'],
        'videoThumbnailUrl': json['video_thumbnail_url'],
        'videoUrl': json['video_url'],
        'createdAt': CreatedAtFromJSON(json['created_at']),
        'updatedAt': UpdatedAtFromJSON(json['updated_at']),
        'status': json['status'],
        'appliedApplication': json['applied_application'] == null ? undefined : AppDbModelDocumentVideoProcessingApplicationFromJSON(json['applied_application']),
    };
}

export function SchemaUserVideoCardToJSON(json: any): SchemaUserVideoCard {
    return SchemaUserVideoCardToJSONTyped(json, false);
}

export function SchemaUserVideoCardToJSONTyped(value?: SchemaUserVideoCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_duration': value['videoDuration'],
        'video_aspect_ratio': VideoAspectRatioToJSON(value['videoAspectRatio']),
        'video_title': value['videoTitle'],
        'video_id': value['videoId'],
        'video_thumbnail_url': value['videoThumbnailUrl'],
        'video_url': value['videoUrl'],
        'created_at': CreatedAtToJSON(value['createdAt']),
        'updated_at': UpdatedAtToJSON(value['updatedAt']),
        'status': value['status'],
        'applied_application': AppDbModelDocumentVideoProcessingApplicationToJSON(value['appliedApplication']),
    };
}

