/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoType } from './VideoType';
import {
    VideoTypeFromJSON,
    VideoTypeFromJSONTyped,
    VideoTypeToJSON,
    VideoTypeToJSONTyped,
} from './VideoType';
import type { VideoAspectRatio } from './VideoAspectRatio';
import {
    VideoAspectRatioFromJSON,
    VideoAspectRatioFromJSONTyped,
    VideoAspectRatioToJSON,
    VideoAspectRatioToJSONTyped,
} from './VideoAspectRatio';
import type { CreatedAt } from './CreatedAt';
import {
    CreatedAtFromJSON,
    CreatedAtFromJSONTyped,
    CreatedAtToJSON,
    CreatedAtToJSONTyped,
} from './CreatedAt';
import type { DissaminateOnSocialMediaPlatforms } from './DissaminateOnSocialMediaPlatforms';
import {
    DissaminateOnSocialMediaPlatformsFromJSON,
    DissaminateOnSocialMediaPlatformsFromJSONTyped,
    DissaminateOnSocialMediaPlatformsToJSON,
    DissaminateOnSocialMediaPlatformsToJSONTyped,
} from './DissaminateOnSocialMediaPlatforms';
import type { VideoFormat } from './VideoFormat';
import {
    VideoFormatFromJSON,
    VideoFormatFromJSONTyped,
    VideoFormatToJSON,
    VideoFormatToJSONTyped,
} from './VideoFormat';
import type { UpdatedAt } from './UpdatedAt';
import {
    UpdatedAtFromJSON,
    UpdatedAtFromJSONTyped,
    UpdatedAtToJSON,
    UpdatedAtToJSONTyped,
} from './UpdatedAt';
import type { Tags } from './Tags';
import {
    TagsFromJSON,
    TagsFromJSONTyped,
    TagsToJSON,
    TagsToJSONTyped,
} from './Tags';
import type { SchemaUserVideoDetails } from './SchemaUserVideoDetails';
import {
    SchemaUserVideoDetailsFromJSON,
    SchemaUserVideoDetailsFromJSONTyped,
    SchemaUserVideoDetailsToJSON,
    SchemaUserVideoDetailsToJSONTyped,
} from './SchemaUserVideoDetails';

/**
 * 
 * @export
 * @interface SchemaUserSegmentVideo
 */
export interface SchemaUserSegmentVideo {
    /**
     * 
     * @type {SchemaUserVideoDetails}
     * @memberof SchemaUserSegmentVideo
     */
    segmentDetails: SchemaUserVideoDetails;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    parentVideoId: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SchemaUserSegmentVideo
     */
    videoDuration: number | null;
    /**
     * 
     * @type {VideoAspectRatio}
     * @memberof SchemaUserSegmentVideo
     */
    videoAspectRatio: VideoAspectRatio;
    /**
     * 
     * @type {VideoType}
     * @memberof SchemaUserSegmentVideo
     */
    videoType: VideoType;
    /**
     * 
     * @type {VideoFormat}
     * @memberof SchemaUserSegmentVideo
     */
    videoFormat: VideoFormat;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    videoResolution: string;
    /**
     * 
     * @type {DissaminateOnSocialMediaPlatforms}
     * @memberof SchemaUserSegmentVideo
     */
    dissaminateOnSocialMediaPlatforms: DissaminateOnSocialMediaPlatforms;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    shortDescription: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    longDescription: string;
    /**
     * 
     * @type {Tags}
     * @memberof SchemaUserSegmentVideo
     */
    tags: Tags;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    thumbnailUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideo
     */
    videoUrl?: string | null;
    /**
     * 
     * @type {CreatedAt}
     * @memberof SchemaUserSegmentVideo
     */
    createdAt: CreatedAt;
    /**
     * 
     * @type {UpdatedAt}
     * @memberof SchemaUserSegmentVideo
     */
    updatedAt: UpdatedAt;
}



/**
 * Check if a given object implements the SchemaUserSegmentVideo interface.
 */
export function instanceOfSchemaUserSegmentVideo(value: object): value is SchemaUserSegmentVideo {
    if (!('segmentDetails' in value) || value['segmentDetails'] === undefined) return false;
    if (!('parentVideoId' in value) || value['parentVideoId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('videoDuration' in value) || value['videoDuration'] === undefined) return false;
    if (!('videoAspectRatio' in value) || value['videoAspectRatio'] === undefined) return false;
    if (!('videoType' in value) || value['videoType'] === undefined) return false;
    if (!('videoFormat' in value) || value['videoFormat'] === undefined) return false;
    if (!('videoResolution' in value) || value['videoResolution'] === undefined) return false;
    if (!('dissaminateOnSocialMediaPlatforms' in value) || value['dissaminateOnSocialMediaPlatforms'] === undefined) return false;
    if (!('shortDescription' in value) || value['shortDescription'] === undefined) return false;
    if (!('longDescription' in value) || value['longDescription'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SchemaUserSegmentVideoFromJSON(json: any): SchemaUserSegmentVideo {
    return SchemaUserSegmentVideoFromJSONTyped(json, false);
}

export function SchemaUserSegmentVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaUserSegmentVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'segmentDetails': SchemaUserVideoDetailsFromJSON(json['segment_details']),
        'parentVideoId': json['parent_video_id'],
        'name': json['name'],
        'videoDuration': json['video_duration'],
        'videoAspectRatio': VideoAspectRatioFromJSON(json['video_aspect_ratio']),
        'videoType': VideoTypeFromJSON(json['video_type']),
        'videoFormat': VideoFormatFromJSON(json['video_format']),
        'videoResolution': json['video_resolution'],
        'dissaminateOnSocialMediaPlatforms': DissaminateOnSocialMediaPlatformsFromJSON(json['dissaminate_on_social_media_platforms']),
        'shortDescription': json['short_description'],
        'longDescription': json['long_description'],
        'tags': TagsFromJSON(json['tags']),
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'videoUrl': json['video_url'] == null ? undefined : json['video_url'],
        'createdAt': CreatedAtFromJSON(json['created_at']),
        'updatedAt': UpdatedAtFromJSON(json['updated_at']),
    };
}

export function SchemaUserSegmentVideoToJSON(json: any): SchemaUserSegmentVideo {
    return SchemaUserSegmentVideoToJSONTyped(json, false);
}

export function SchemaUserSegmentVideoToJSONTyped(value?: SchemaUserSegmentVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'segment_details': SchemaUserVideoDetailsToJSON(value['segmentDetails']),
        'parent_video_id': value['parentVideoId'],
        'name': value['name'],
        'video_duration': value['videoDuration'],
        'video_aspect_ratio': VideoAspectRatioToJSON(value['videoAspectRatio']),
        'video_type': VideoTypeToJSON(value['videoType']),
        'video_format': VideoFormatToJSON(value['videoFormat']),
        'video_resolution': value['videoResolution'],
        'dissaminate_on_social_media_platforms': DissaminateOnSocialMediaPlatformsToJSON(value['dissaminateOnSocialMediaPlatforms']),
        'short_description': value['shortDescription'],
        'long_description': value['longDescription'],
        'tags': TagsToJSON(value['tags']),
        'thumbnail_url': value['thumbnailUrl'],
        'video_url': value['videoUrl'],
        'created_at': CreatedAtToJSON(value['createdAt']),
        'updated_at': UpdatedAtToJSON(value['updatedAt']),
    };
}

