/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaUserSegmentVideo } from './SchemaUserSegmentVideo';
import {
    SchemaUserSegmentVideoFromJSON,
    SchemaUserSegmentVideoFromJSONTyped,
    SchemaUserSegmentVideoToJSON,
    SchemaUserSegmentVideoToJSONTyped,
} from './SchemaUserSegmentVideo';

/**
 * 
 * @export
 * @interface SchemaUserSegmentVideoList
 */
export interface SchemaUserSegmentVideoList {
    /**
     * 
     * @type {string}
     * @memberof SchemaUserSegmentVideoList
     */
    videoId: string;
    /**
     * 
     * @type {Array<SchemaUserSegmentVideo>}
     * @memberof SchemaUserSegmentVideoList
     */
    userSegmentVideos: Array<SchemaUserSegmentVideo>;
}

/**
 * Check if a given object implements the SchemaUserSegmentVideoList interface.
 */
export function instanceOfSchemaUserSegmentVideoList(value: object): value is SchemaUserSegmentVideoList {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('userSegmentVideos' in value) || value['userSegmentVideos'] === undefined) return false;
    return true;
}

export function SchemaUserSegmentVideoListFromJSON(json: any): SchemaUserSegmentVideoList {
    return SchemaUserSegmentVideoListFromJSONTyped(json, false);
}

export function SchemaUserSegmentVideoListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaUserSegmentVideoList {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['video_id'],
        'userSegmentVideos': ((json['user_segment_videos'] as Array<any>).map(SchemaUserSegmentVideoFromJSON)),
    };
}

export function SchemaUserSegmentVideoListToJSON(json: any): SchemaUserSegmentVideoList {
    return SchemaUserSegmentVideoListToJSONTyped(json, false);
}

export function SchemaUserSegmentVideoListToJSONTyped(value?: SchemaUserSegmentVideoList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_id': value['videoId'],
        'user_segment_videos': ((value['userSegmentVideos'] as Array<any>).map(SchemaUserSegmentVideoToJSON)),
    };
}

