/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoType } from './VideoType';
import {
    VideoTypeFromJSON,
    VideoTypeFromJSONTyped,
    VideoTypeToJSON,
    VideoTypeToJSONTyped,
} from './VideoType';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';
import type { VideoAspectRatio } from './VideoAspectRatio';
import {
    VideoAspectRatioFromJSON,
    VideoAspectRatioFromJSONTyped,
    VideoAspectRatioToJSON,
    VideoAspectRatioToJSONTyped,
} from './VideoAspectRatio';
import type { CroppingOperator } from './CroppingOperator';
import {
    CroppingOperatorFromJSON,
    CroppingOperatorFromJSONTyped,
    CroppingOperatorToJSON,
    CroppingOperatorToJSONTyped,
} from './CroppingOperator';
import type { ResolutionMode } from './ResolutionMode';
import {
    ResolutionModeFromJSON,
    ResolutionModeFromJSONTyped,
    ResolutionModeToJSON,
    ResolutionModeToJSONTyped,
} from './ResolutionMode';
import type { SocialMediaPlatform } from './SocialMediaPlatform';
import {
    SocialMediaPlatformFromJSON,
    SocialMediaPlatformFromJSONTyped,
    SocialMediaPlatformToJSON,
    SocialMediaPlatformToJSONTyped,
} from './SocialMediaPlatform';
import type { VideoPeopleContext } from './VideoPeopleContext';
import {
    VideoPeopleContextFromJSON,
    VideoPeopleContextFromJSONTyped,
    VideoPeopleContextToJSON,
    VideoPeopleContextToJSONTyped,
} from './VideoPeopleContext';
import type { SubtitleApplication } from './SubtitleApplication';
import {
    SubtitleApplicationFromJSON,
    SubtitleApplicationFromJSONTyped,
    SubtitleApplicationToJSON,
    SubtitleApplicationToJSONTyped,
} from './SubtitleApplication';
import type { AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication } from './AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication';
import {
    AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSON,
    AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSONTyped,
    AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSON,
    AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSONTyped,
} from './AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication';
import type { VideoFormat } from './VideoFormat';
import {
    VideoFormatFromJSON,
    VideoFormatFromJSONTyped,
    VideoFormatToJSON,
    VideoFormatToJSONTyped,
} from './VideoFormat';
import type { ManualCropping } from './ManualCropping';
import {
    ManualCroppingFromJSON,
    ManualCroppingFromJSONTyped,
    ManualCroppingToJSON,
    ManualCroppingToJSONTyped,
} from './ManualCropping';
import type { TrimApplication } from './TrimApplication';
import {
    TrimApplicationFromJSON,
    TrimApplicationFromJSONTyped,
    TrimApplicationToJSON,
    TrimApplicationToJSONTyped,
} from './TrimApplication';

/**
 * Settings for Subtiter video processing.
 * @export
 * @interface ShortConfigJsonInput
 */
export interface ShortConfigJsonInput {
    /**
     * ID of the video.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    videoId?: string;
    /**
     * ID of the user.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    userId?: string;
    /**
     * Context of the video, e.g., podcast, solo, vlog, interview, presentation.
     * @type {VideoPeopleContext}
     * @memberof ShortConfigJsonInput
     */
    videoPeopleContext?: VideoPeopleContext;
    /**
     * Original video thumbnail url.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    originalVideoThumbnailUrl?: string;
    /**
     * Original video duration in seconds.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    originalVideoDurationInSeconds?: number;
    /**
     * Target length for short videos in seconds. Use -1 for auto-detection.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    targetShortVideoDurationInSeconds?: number;
    /**
     * Original video trim start in seconds.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    targetVideoTrimStartInSeconds?: number;
    /**
     * Original video trim end in seconds.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    targetVideoTrimEndInSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    howManyPeopleInVideo?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJsonInput
     */
    dissaminateOnSocialMedia?: boolean;
    /**
     * Number of segments to extract from the video.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    segmentCount?: number;
    /**
     * Language code for transcription, e.g., 'en', 'tr'. 'auto-detect' is also an option.
     * @type {LanguageCode}
     * @memberof ShortConfigJsonInput
     */
    videoLanguageCode?: LanguageCode;
    /**
     * e.g., 16:9, 9:16, 1:1.
     * @type {VideoAspectRatio}
     * @memberof ShortConfigJsonInput
     */
    videoAspectRatio?: VideoAspectRatio;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJsonInput
     */
    generateEngagingCaptions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJsonInput
     */
    useEmojisInAssWords?: boolean;
    /**
     * Type of the video, e.g., video, image, gif.
     * @type {VideoType}
     * @memberof ShortConfigJsonInput
     */
    videoType?: VideoType;
    /**
     * Format of the video, e.g., mp4, mov, avi.
     * @type {VideoFormat}
     * @memberof ShortConfigJsonInput
     */
    videoFormat?: VideoFormat;
    /**
     * Resolution of the video in pixels. Use -1 for auto-detection.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    videoResolution?: string;
    /**
     * List of social media platforms to dissaminate on.
     * @type {Array<SocialMediaPlatform>}
     * @memberof ShortConfigJsonInput
     */
    dissaminateOnSocialMediaPlatforms?: Array<SocialMediaPlatform>;
    /**
     * Time interval for reference images in seconds.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    croppingReferenceImageTimeInterval?: number;
    /**
     * Operator for cropping the video.
     * @type {CroppingOperator}
     * @memberof ShortConfigJsonInput
     */
    croppingOperator?: CroppingOperator;
    /**
     * 
     * @type {ManualCropping}
     * @memberof ShortConfigJsonInput
     */
    manualCropping?: ManualCropping | null;
    /**
     * Number of threads to use for ffmpeg.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    ffmpegThreadCount?: number;
    /**
     * Preset for ffmpeg.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    ffmpegPreset?: string;
    /**
     * CRF for ffmpeg.
     * @type {number}
     * @memberof ShortConfigJsonInput
     */
    ffmpegCrf?: number;
    /**
     * Video duration category, e.g., '0-10-minutes', '10-20-minutes', '20-30-minutes', '30-40-minutes', '40+-minutes'.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    videoDurationCategory?: string;
    /**
     * Whether the task is running on a fargate task.
     * @type {boolean}
     * @memberof ShortConfigJsonInput
     */
    isFargateTask?: boolean;
    /**
     * S3 bucket name.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    s3BucketName?: string;
    /**
     * Fargate execution role.
     * @type {string}
     * @memberof ShortConfigJsonInput
     */
    fARGATEEXECUTIONROLE?: string;
    /**
     * Target resolution mode.
     * @type {ResolutionMode}
     * @memberof ShortConfigJsonInput
     */
    targetResolutionMode?: ResolutionMode;
    /**
     * Applied application.
     * @type {AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication}
     * @memberof ShortConfigJsonInput
     */
    appliedApplication?: AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplication;
    /**
     * Subtitle application.
     * @type {SubtitleApplication}
     * @memberof ShortConfigJsonInput
     */
    subtitleApplication?: SubtitleApplication;
    /**
     * Trim application.
     * @type {TrimApplication}
     * @memberof ShortConfigJsonInput
     */
    trimApplication?: TrimApplication;
}



/**
 * Check if a given object implements the ShortConfigJsonInput interface.
 */
export function instanceOfShortConfigJsonInput(value: object): value is ShortConfigJsonInput {
    return true;
}

export function ShortConfigJsonInputFromJSON(json: any): ShortConfigJsonInput {
    return ShortConfigJsonInputFromJSONTyped(json, false);
}

export function ShortConfigJsonInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortConfigJsonInput {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['video_id'] == null ? undefined : json['video_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'videoPeopleContext': json['video_people_context'] == null ? undefined : VideoPeopleContextFromJSON(json['video_people_context']),
        'originalVideoThumbnailUrl': json['original_video_thumbnail_url'] == null ? undefined : json['original_video_thumbnail_url'],
        'originalVideoDurationInSeconds': json['original_video_duration_in_seconds'] == null ? undefined : json['original_video_duration_in_seconds'],
        'targetShortVideoDurationInSeconds': json['target_short_video_duration_in_seconds'] == null ? undefined : json['target_short_video_duration_in_seconds'],
        'targetVideoTrimStartInSeconds': json['target_video_trim_start_in_seconds'] == null ? undefined : json['target_video_trim_start_in_seconds'],
        'targetVideoTrimEndInSeconds': json['target_video_trim_end_in_seconds'] == null ? undefined : json['target_video_trim_end_in_seconds'],
        'howManyPeopleInVideo': json['how_many_people_in_video'] == null ? undefined : json['how_many_people_in_video'],
        'dissaminateOnSocialMedia': json['dissaminate_on_social_media'] == null ? undefined : json['dissaminate_on_social_media'],
        'segmentCount': json['segment_count'] == null ? undefined : json['segment_count'],
        'videoLanguageCode': json['video_language_code'] == null ? undefined : LanguageCodeFromJSON(json['video_language_code']),
        'videoAspectRatio': json['video_aspect_ratio'] == null ? undefined : VideoAspectRatioFromJSON(json['video_aspect_ratio']),
        'generateEngagingCaptions': json['generate_engaging_captions'] == null ? undefined : json['generate_engaging_captions'],
        'useEmojisInAssWords': json['use_emojis_in_ass_words'] == null ? undefined : json['use_emojis_in_ass_words'],
        'videoType': json['video_type'] == null ? undefined : VideoTypeFromJSON(json['video_type']),
        'videoFormat': json['video_format'] == null ? undefined : VideoFormatFromJSON(json['video_format']),
        'videoResolution': json['video_resolution'] == null ? undefined : json['video_resolution'],
        'dissaminateOnSocialMediaPlatforms': json['dissaminate_on_social_media_platforms'] == null ? undefined : ((json['dissaminate_on_social_media_platforms'] as Array<any>).map(SocialMediaPlatformFromJSON)),
        'croppingReferenceImageTimeInterval': json['cropping_reference_image_time_interval'] == null ? undefined : json['cropping_reference_image_time_interval'],
        'croppingOperator': json['cropping_operator'] == null ? undefined : CroppingOperatorFromJSON(json['cropping_operator']),
        'manualCropping': json['manual_cropping'] == null ? undefined : ManualCroppingFromJSON(json['manual_cropping']),
        'ffmpegThreadCount': json['ffmpeg_thread_count'] == null ? undefined : json['ffmpeg_thread_count'],
        'ffmpegPreset': json['ffmpeg_preset'] == null ? undefined : json['ffmpeg_preset'],
        'ffmpegCrf': json['ffmpeg_crf'] == null ? undefined : json['ffmpeg_crf'],
        'videoDurationCategory': json['video_duration_category'] == null ? undefined : json['video_duration_category'],
        'isFargateTask': json['is_fargate_task'] == null ? undefined : json['is_fargate_task'],
        's3BucketName': json['s3_bucket_name'] == null ? undefined : json['s3_bucket_name'],
        'fARGATEEXECUTIONROLE': json['FARGATE_EXECUTION_ROLE'] == null ? undefined : json['FARGATE_EXECUTION_ROLE'],
        'targetResolutionMode': json['target_resolution_mode'] == null ? undefined : ResolutionModeFromJSON(json['target_resolution_mode']),
        'appliedApplication': json['applied_application'] == null ? undefined : AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationFromJSON(json['applied_application']),
        'subtitleApplication': json['subtitle_application'] == null ? undefined : SubtitleApplicationFromJSON(json['subtitle_application']),
        'trimApplication': json['trim_application'] == null ? undefined : TrimApplicationFromJSON(json['trim_application']),
    };
}

export function ShortConfigJsonInputToJSON(json: any): ShortConfigJsonInput {
    return ShortConfigJsonInputToJSONTyped(json, false);
}

export function ShortConfigJsonInputToJSONTyped(value?: ShortConfigJsonInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'video_id': value['videoId'],
        'user_id': value['userId'],
        'video_people_context': VideoPeopleContextToJSON(value['videoPeopleContext']),
        'original_video_thumbnail_url': value['originalVideoThumbnailUrl'],
        'original_video_duration_in_seconds': value['originalVideoDurationInSeconds'],
        'target_short_video_duration_in_seconds': value['targetShortVideoDurationInSeconds'],
        'target_video_trim_start_in_seconds': value['targetVideoTrimStartInSeconds'],
        'target_video_trim_end_in_seconds': value['targetVideoTrimEndInSeconds'],
        'how_many_people_in_video': value['howManyPeopleInVideo'],
        'dissaminate_on_social_media': value['dissaminateOnSocialMedia'],
        'segment_count': value['segmentCount'],
        'video_language_code': LanguageCodeToJSON(value['videoLanguageCode']),
        'video_aspect_ratio': VideoAspectRatioToJSON(value['videoAspectRatio']),
        'generate_engaging_captions': value['generateEngagingCaptions'],
        'use_emojis_in_ass_words': value['useEmojisInAssWords'],
        'video_type': VideoTypeToJSON(value['videoType']),
        'video_format': VideoFormatToJSON(value['videoFormat']),
        'video_resolution': value['videoResolution'],
        'dissaminate_on_social_media_platforms': value['dissaminateOnSocialMediaPlatforms'] == null ? undefined : ((value['dissaminateOnSocialMediaPlatforms'] as Array<any>).map(SocialMediaPlatformToJSON)),
        'cropping_reference_image_time_interval': value['croppingReferenceImageTimeInterval'],
        'cropping_operator': CroppingOperatorToJSON(value['croppingOperator']),
        'manual_cropping': ManualCroppingToJSON(value['manualCropping']),
        'ffmpeg_thread_count': value['ffmpegThreadCount'],
        'ffmpeg_preset': value['ffmpegPreset'],
        'ffmpeg_crf': value['ffmpegCrf'],
        'video_duration_category': value['videoDurationCategory'],
        'is_fargate_task': value['isFargateTask'],
        's3_bucket_name': value['s3BucketName'],
        'FARGATE_EXECUTION_ROLE': value['fARGATEEXECUTIONROLE'],
        'target_resolution_mode': ResolutionModeToJSON(value['targetResolutionMode']),
        'applied_application': AppSubtitercmdClippercmdModelShortConfigModelVideoProcessingApplicationToJSON(value['appliedApplication']),
        'subtitle_application': SubtitleApplicationToJSON(value['subtitleApplication']),
        'trim_application': TrimApplicationToJSON(value['trimApplication']),
    };
}

