/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppDbModelDocumentVideoProcessingApplication } from './AppDbModelDocumentVideoProcessingApplication';
import {
    AppDbModelDocumentVideoProcessingApplicationFromJSON,
    AppDbModelDocumentVideoProcessingApplicationFromJSONTyped,
    AppDbModelDocumentVideoProcessingApplicationToJSON,
    AppDbModelDocumentVideoProcessingApplicationToJSONTyped,
} from './AppDbModelDocumentVideoProcessingApplication';
import type { VideoAspectRatio } from './VideoAspectRatio';
import {
    VideoAspectRatioFromJSON,
    VideoAspectRatioFromJSONTyped,
    VideoAspectRatioToJSON,
    VideoAspectRatioToJSONTyped,
} from './VideoAspectRatio';
import type { CroppingOperator } from './CroppingOperator';
import {
    CroppingOperatorFromJSON,
    CroppingOperatorFromJSONTyped,
    CroppingOperatorToJSON,
    CroppingOperatorToJSONTyped,
} from './CroppingOperator';
import type { ResolutionMode } from './ResolutionMode';
import {
    ResolutionModeFromJSON,
    ResolutionModeFromJSONTyped,
    ResolutionModeToJSON,
    ResolutionModeToJSONTyped,
} from './ResolutionMode';
import type { SubtitleApplication } from './SubtitleApplication';
import {
    SubtitleApplicationFromJSON,
    SubtitleApplicationFromJSONTyped,
    SubtitleApplicationToJSON,
    SubtitleApplicationToJSONTyped,
} from './SubtitleApplication';
import type { SubtitleCapitalizationMethod } from './SubtitleCapitalizationMethod';
import {
    SubtitleCapitalizationMethodFromJSON,
    SubtitleCapitalizationMethodFromJSONTyped,
    SubtitleCapitalizationMethodToJSON,
    SubtitleCapitalizationMethodToJSONTyped,
} from './SubtitleCapitalizationMethod';
import type { VideoFormat } from './VideoFormat';
import {
    VideoFormatFromJSON,
    VideoFormatFromJSONTyped,
    VideoFormatToJSON,
    VideoFormatToJSONTyped,
} from './VideoFormat';
import type { ManualCropping } from './ManualCropping';
import {
    ManualCroppingFromJSON,
    ManualCroppingFromJSONTyped,
    ManualCroppingToJSON,
    ManualCroppingToJSONTyped,
} from './ManualCropping';
import type { VideoType } from './VideoType';
import {
    VideoTypeFromJSON,
    VideoTypeFromJSONTyped,
    VideoTypeToJSON,
    VideoTypeToJSONTyped,
} from './VideoType';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';
import type { SocialMediaPlatform } from './SocialMediaPlatform';
import {
    SocialMediaPlatformFromJSON,
    SocialMediaPlatformFromJSONTyped,
    SocialMediaPlatformToJSON,
    SocialMediaPlatformToJSONTyped,
} from './SocialMediaPlatform';
import type { VideoPeopleContext } from './VideoPeopleContext';
import {
    VideoPeopleContextFromJSON,
    VideoPeopleContextFromJSONTyped,
    VideoPeopleContextToJSON,
    VideoPeopleContextToJSONTyped,
} from './VideoPeopleContext';
import type { TrimApplication } from './TrimApplication';
import {
    TrimApplicationFromJSON,
    TrimApplicationFromJSONTyped,
    TrimApplicationToJSON,
    TrimApplicationToJSONTyped,
} from './TrimApplication';

/**
 * Settings for Subtiter video processing.
 * @export
 * @interface ShortConfigJson
 */
export interface ShortConfigJson {
    /**
     * Style of the subtitles, e.g., 'middle', 'bottom', 'top'.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleStyle?: string;
    /**
     * 
     * @type {SubtitleCapitalizationMethod}
     * @memberof ShortConfigJson
     */
    subtitleCapitalizationMethod?: SubtitleCapitalizationMethod;
    /**
     * Context of the video, e.g., podcast, solo, vlog, interview, presentation.
     * @type {VideoPeopleContext}
     * @memberof ShortConfigJson
     */
    videoPeopleContext?: VideoPeopleContext;
    /**
     * Original video thumbnail url.
     * @type {string}
     * @memberof ShortConfigJson
     */
    originalVideoThumbnailUrl?: string;
    /**
     * Original video duration in seconds.
     * @type {number}
     * @memberof ShortConfigJson
     */
    originalVideoDurationInSeconds?: number;
    /**
     * Target length for short videos in seconds. Use -1 for auto-detection.
     * @type {number}
     * @memberof ShortConfigJson
     */
    targetShortVideoDurationInSeconds?: number;
    /**
     * Original video trim start in seconds.
     * @type {number}
     * @memberof ShortConfigJson
     */
    targetVideoTrimStartInSeconds?: number;
    /**
     * Original video trim end in seconds.
     * @type {number}
     * @memberof ShortConfigJson
     */
    targetVideoTrimEndInSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof ShortConfigJson
     */
    howManyPeopleInVideo?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    dissaminateOnSocialMedia?: boolean;
    /**
     * Number of segments to extract from the video.
     * @type {number}
     * @memberof ShortConfigJson
     */
    segmentCount?: number;
    /**
     * Language code for transcription, e.g., 'en', 'tr'. 'auto-detect' is also an option.
     * @type {LanguageCode}
     * @memberof ShortConfigJson
     */
    languageCode?: LanguageCode;
    /**
     * e.g., 16:9, 9:16, 1:1.
     * @type {VideoAspectRatio}
     * @memberof ShortConfigJson
     */
    videoAspectRatio?: VideoAspectRatio;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    generateEngagingCaptions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    useEmojisInAssWords?: boolean;
    /**
     * Type of the video, e.g., video, image, gif.
     * @type {VideoType}
     * @memberof ShortConfigJson
     */
    videoType?: VideoType;
    /**
     * Format of the video, e.g., mp4, mov, avi.
     * @type {VideoFormat}
     * @memberof ShortConfigJson
     */
    videoFormat?: VideoFormat;
    /**
     * Resolution of the video in pixels. Use -1 for auto-detection.
     * @type {string}
     * @memberof ShortConfigJson
     */
    videoResolution?: string;
    /**
     * List of social media platforms to dissaminate on.
     * @type {Array<SocialMediaPlatform>}
     * @memberof ShortConfigJson
     */
    dissaminateOnSocialMediaPlatforms?: Array<SocialMediaPlatform>;
    /**
     * Time interval for reference images in seconds.
     * @type {number}
     * @memberof ShortConfigJson
     */
    croppingReferenceImageTimeInterval?: number;
    /**
     * Operator for cropping the video.
     * @type {CroppingOperator}
     * @memberof ShortConfigJson
     */
    croppingOperator?: CroppingOperator;
    /**
     * 
     * @type {ManualCropping}
     * @memberof ShortConfigJson
     */
    manualCropping?: ManualCropping | null;
    /**
     * Number of threads to use for ffmpeg.
     * @type {number}
     * @memberof ShortConfigJson
     */
    ffmpegThreadCount?: number;
    /**
     * Preset for ffmpeg.
     * @type {string}
     * @memberof ShortConfigJson
     */
    ffmpegPreset?: string;
    /**
     * CRF for ffmpeg.
     * @type {number}
     * @memberof ShortConfigJson
     */
    ffmpegCrf?: number;
    /**
     * 
     * @type {LanguageCode}
     * @memberof ShortConfigJson
     */
    subtitleTrainslateToLanguageCode?: LanguageCode | null;
    /**
     * Video duration category, e.g., '0-10-minutes', '10-20-minutes', '20-30-minutes', '30-40-minutes', '40+-minutes'.
     * @type {string}
     * @memberof ShortConfigJson
     */
    videoDurationCategory?: string;
    /**
     * Position of the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitlePosition?: string;
    /**
     * Background color for the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleBoxFontColor?: string;
    /**
     * Transparency for the subtitles.
     * @type {number}
     * @memberof ShortConfigJson
     */
    subtitleBoxTransparency?: number;
    /**
     * Background color for the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleBoxBackgroundColor?: string;
    /**
     * Color for the inactive part of the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleInactiveColor?: string;
    /**
     * Color for the active (highlighted) part of the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleActiveColor?: string;
    /**
     * Corner radius for the subtitles.
     * @type {number}
     * @memberof ShortConfigJson
     */
    subtitleBoxCornerRadius?: number;
    /**
     * Compensation factor for word width.
     * @type {number}
     * @memberof ShortConfigJson
     */
    subtitleBoxWidthCompensation?: number;
    /**
     * Border thickness for the subtitles.
     * @type {number}
     * @memberof ShortConfigJson
     */
    subtitleBoxBorderThickness?: number;
    /**
     * Font size for the subtitles.
     * @type {number}
     * @memberof ShortConfigJson
     */
    subtitleFontSize?: number;
    /**
     * Font name for the subtitles.
     * @type {string}
     * @memberof ShortConfigJson
     */
    subtitleFontName?: string;
    /**
     * Whether to use bold font for the subtitles.
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    subtitleFontBold?: boolean;
    /**
     * Whether to use italic font for the subtitles.
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    subtitleFontItalic?: boolean;
    /**
     * Whether to use underline font for the subtitles.
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    subtitleFontUnderline?: boolean;
    /**
     * Whether the task is running on a fargate task.
     * @type {boolean}
     * @memberof ShortConfigJson
     */
    isFargateTask?: boolean;
    /**
     * S3 bucket name.
     * @type {string}
     * @memberof ShortConfigJson
     */
    s3BucketName?: string;
    /**
     * Fargate execution role.
     * @type {string}
     * @memberof ShortConfigJson
     */
    fARGATEEXECUTIONROLE?: string;
    /**
     * Target resolution mode.
     * @type {ResolutionMode}
     * @memberof ShortConfigJson
     */
    targetResolutionMode?: ResolutionMode;
    /**
     * Applied application.
     * @type {AppDbModelDocumentVideoProcessingApplication}
     * @memberof ShortConfigJson
     */
    appliedApplication?: AppDbModelDocumentVideoProcessingApplication;
    /**
     * Subtitle application.
     * @type {SubtitleApplication}
     * @memberof ShortConfigJson
     */
    subtitleApplication?: SubtitleApplication;
    /**
     * Trim application.
     * @type {TrimApplication}
     * @memberof ShortConfigJson
     */
    trimApplication?: TrimApplication;
}



/**
 * Check if a given object implements the ShortConfigJson interface.
 */
export function instanceOfShortConfigJson(value: object): value is ShortConfigJson {
    return true;
}

export function ShortConfigJsonFromJSON(json: any): ShortConfigJson {
    return ShortConfigJsonFromJSONTyped(json, false);
}

export function ShortConfigJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortConfigJson {
    if (json == null) {
        return json;
    }
    return {
        
        'subtitleStyle': json['subtitle_style'] == null ? undefined : json['subtitle_style'],
        'subtitleCapitalizationMethod': json['subtitle_capitalization_method'] == null ? undefined : SubtitleCapitalizationMethodFromJSON(json['subtitle_capitalization_method']),
        'videoPeopleContext': json['video_people_context'] == null ? undefined : VideoPeopleContextFromJSON(json['video_people_context']),
        'originalVideoThumbnailUrl': json['original_video_thumbnail_url'] == null ? undefined : json['original_video_thumbnail_url'],
        'originalVideoDurationInSeconds': json['original_video_duration_in_seconds'] == null ? undefined : json['original_video_duration_in_seconds'],
        'targetShortVideoDurationInSeconds': json['target_short_video_duration_in_seconds'] == null ? undefined : json['target_short_video_duration_in_seconds'],
        'targetVideoTrimStartInSeconds': json['target_video_trim_start_in_seconds'] == null ? undefined : json['target_video_trim_start_in_seconds'],
        'targetVideoTrimEndInSeconds': json['target_video_trim_end_in_seconds'] == null ? undefined : json['target_video_trim_end_in_seconds'],
        'howManyPeopleInVideo': json['how_many_people_in_video'] == null ? undefined : json['how_many_people_in_video'],
        'dissaminateOnSocialMedia': json['dissaminate_on_social_media'] == null ? undefined : json['dissaminate_on_social_media'],
        'segmentCount': json['segment_count'] == null ? undefined : json['segment_count'],
        'languageCode': json['language_code'] == null ? undefined : LanguageCodeFromJSON(json['language_code']),
        'videoAspectRatio': json['video_aspect_ratio'] == null ? undefined : VideoAspectRatioFromJSON(json['video_aspect_ratio']),
        'generateEngagingCaptions': json['generate_engaging_captions'] == null ? undefined : json['generate_engaging_captions'],
        'useEmojisInAssWords': json['use_emojis_in_ass_words'] == null ? undefined : json['use_emojis_in_ass_words'],
        'videoType': json['video_type'] == null ? undefined : VideoTypeFromJSON(json['video_type']),
        'videoFormat': json['video_format'] == null ? undefined : VideoFormatFromJSON(json['video_format']),
        'videoResolution': json['video_resolution'] == null ? undefined : json['video_resolution'],
        'dissaminateOnSocialMediaPlatforms': json['dissaminate_on_social_media_platforms'] == null ? undefined : ((json['dissaminate_on_social_media_platforms'] as Array<any>).map(SocialMediaPlatformFromJSON)),
        'croppingReferenceImageTimeInterval': json['cropping_reference_image_time_interval'] == null ? undefined : json['cropping_reference_image_time_interval'],
        'croppingOperator': json['cropping_operator'] == null ? undefined : CroppingOperatorFromJSON(json['cropping_operator']),
        'manualCropping': json['manual_cropping'] == null ? undefined : ManualCroppingFromJSON(json['manual_cropping']),
        'ffmpegThreadCount': json['ffmpeg_thread_count'] == null ? undefined : json['ffmpeg_thread_count'],
        'ffmpegPreset': json['ffmpeg_preset'] == null ? undefined : json['ffmpeg_preset'],
        'ffmpegCrf': json['ffmpeg_crf'] == null ? undefined : json['ffmpeg_crf'],
        'subtitleTrainslateToLanguageCode': json['subtitle_trainslate_to_language_code'] == null ? undefined : LanguageCodeFromJSON(json['subtitle_trainslate_to_language_code']),
        'videoDurationCategory': json['video_duration_category'] == null ? undefined : json['video_duration_category'],
        'subtitlePosition': json['subtitle_position'] == null ? undefined : json['subtitle_position'],
        'subtitleBoxFontColor': json['subtitle_box_font_color'] == null ? undefined : json['subtitle_box_font_color'],
        'subtitleBoxTransparency': json['subtitle_box_transparency'] == null ? undefined : json['subtitle_box_transparency'],
        'subtitleBoxBackgroundColor': json['subtitle_box_background_color'] == null ? undefined : json['subtitle_box_background_color'],
        'subtitleInactiveColor': json['subtitle_inactive_color'] == null ? undefined : json['subtitle_inactive_color'],
        'subtitleActiveColor': json['subtitle_active_color'] == null ? undefined : json['subtitle_active_color'],
        'subtitleBoxCornerRadius': json['subtitle_box_corner_radius'] == null ? undefined : json['subtitle_box_corner_radius'],
        'subtitleBoxWidthCompensation': json['subtitle_box_width_compensation'] == null ? undefined : json['subtitle_box_width_compensation'],
        'subtitleBoxBorderThickness': json['subtitle_box_border_thickness'] == null ? undefined : json['subtitle_box_border_thickness'],
        'subtitleFontSize': json['subtitle_font_size'] == null ? undefined : json['subtitle_font_size'],
        'subtitleFontName': json['subtitle_font_name'] == null ? undefined : json['subtitle_font_name'],
        'subtitleFontBold': json['subtitle_font_bold'] == null ? undefined : json['subtitle_font_bold'],
        'subtitleFontItalic': json['subtitle_font_italic'] == null ? undefined : json['subtitle_font_italic'],
        'subtitleFontUnderline': json['subtitle_font_underline'] == null ? undefined : json['subtitle_font_underline'],
        'isFargateTask': json['is_fargate_task'] == null ? undefined : json['is_fargate_task'],
        's3BucketName': json['s3_bucket_name'] == null ? undefined : json['s3_bucket_name'],
        'fARGATEEXECUTIONROLE': json['FARGATE_EXECUTION_ROLE'] == null ? undefined : json['FARGATE_EXECUTION_ROLE'],
        'targetResolutionMode': json['target_resolution_mode'] == null ? undefined : ResolutionModeFromJSON(json['target_resolution_mode']),
        'appliedApplication': json['applied_application'] == null ? undefined : AppDbModelDocumentVideoProcessingApplicationFromJSON(json['applied_application']),
        'subtitleApplication': json['subtitle_application'] == null ? undefined : SubtitleApplicationFromJSON(json['subtitle_application']),
        'trimApplication': json['trim_application'] == null ? undefined : TrimApplicationFromJSON(json['trim_application']),
    };
}

export function ShortConfigJsonToJSON(json: any): ShortConfigJson {
    return ShortConfigJsonToJSONTyped(json, false);
}

export function ShortConfigJsonToJSONTyped(value?: ShortConfigJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subtitle_style': value['subtitleStyle'],
        'subtitle_capitalization_method': SubtitleCapitalizationMethodToJSON(value['subtitleCapitalizationMethod']),
        'video_people_context': VideoPeopleContextToJSON(value['videoPeopleContext']),
        'original_video_thumbnail_url': value['originalVideoThumbnailUrl'],
        'original_video_duration_in_seconds': value['originalVideoDurationInSeconds'],
        'target_short_video_duration_in_seconds': value['targetShortVideoDurationInSeconds'],
        'target_video_trim_start_in_seconds': value['targetVideoTrimStartInSeconds'],
        'target_video_trim_end_in_seconds': value['targetVideoTrimEndInSeconds'],
        'how_many_people_in_video': value['howManyPeopleInVideo'],
        'dissaminate_on_social_media': value['dissaminateOnSocialMedia'],
        'segment_count': value['segmentCount'],
        'language_code': LanguageCodeToJSON(value['languageCode']),
        'video_aspect_ratio': VideoAspectRatioToJSON(value['videoAspectRatio']),
        'generate_engaging_captions': value['generateEngagingCaptions'],
        'use_emojis_in_ass_words': value['useEmojisInAssWords'],
        'video_type': VideoTypeToJSON(value['videoType']),
        'video_format': VideoFormatToJSON(value['videoFormat']),
        'video_resolution': value['videoResolution'],
        'dissaminate_on_social_media_platforms': value['dissaminateOnSocialMediaPlatforms'] == null ? undefined : ((value['dissaminateOnSocialMediaPlatforms'] as Array<any>).map(SocialMediaPlatformToJSON)),
        'cropping_reference_image_time_interval': value['croppingReferenceImageTimeInterval'],
        'cropping_operator': CroppingOperatorToJSON(value['croppingOperator']),
        'manual_cropping': ManualCroppingToJSON(value['manualCropping']),
        'ffmpeg_thread_count': value['ffmpegThreadCount'],
        'ffmpeg_preset': value['ffmpegPreset'],
        'ffmpeg_crf': value['ffmpegCrf'],
        'subtitle_trainslate_to_language_code': LanguageCodeToJSON(value['subtitleTrainslateToLanguageCode']),
        'video_duration_category': value['videoDurationCategory'],
        'subtitle_position': value['subtitlePosition'],
        'subtitle_box_font_color': value['subtitleBoxFontColor'],
        'subtitle_box_transparency': value['subtitleBoxTransparency'],
        'subtitle_box_background_color': value['subtitleBoxBackgroundColor'],
        'subtitle_inactive_color': value['subtitleInactiveColor'],
        'subtitle_active_color': value['subtitleActiveColor'],
        'subtitle_box_corner_radius': value['subtitleBoxCornerRadius'],
        'subtitle_box_width_compensation': value['subtitleBoxWidthCompensation'],
        'subtitle_box_border_thickness': value['subtitleBoxBorderThickness'],
        'subtitle_font_size': value['subtitleFontSize'],
        'subtitle_font_name': value['subtitleFontName'],
        'subtitle_font_bold': value['subtitleFontBold'],
        'subtitle_font_italic': value['subtitleFontItalic'],
        'subtitle_font_underline': value['subtitleFontUnderline'],
        'is_fargate_task': value['isFargateTask'],
        's3_bucket_name': value['s3BucketName'],
        'FARGATE_EXECUTION_ROLE': value['fARGATEEXECUTIONROLE'],
        'target_resolution_mode': ResolutionModeToJSON(value['targetResolutionMode']),
        'applied_application': AppDbModelDocumentVideoProcessingApplicationToJSON(value['appliedApplication']),
        'subtitle_application': SubtitleApplicationToJSON(value['subtitleApplication']),
        'trim_application': TrimApplicationToJSON(value['trimApplication']),
    };
}

