/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SocialMediaPlatform = {
    Facebook: 'facebook',
    Instagram: 'instagram',
    Twitter: 'twitter',
    Linkedin: 'linkedin',
    Youtube: 'youtube',
    Tiktok: 'tiktok',
    Pinterest: 'pinterest',
    Reddit: 'reddit',
    Snapchat: 'snapchat',
    Telegram: 'telegram'
} as const;
export type SocialMediaPlatform = typeof SocialMediaPlatform[keyof typeof SocialMediaPlatform];


export function instanceOfSocialMediaPlatform(value: any): boolean {
    for (const key in SocialMediaPlatform) {
        if (Object.prototype.hasOwnProperty.call(SocialMediaPlatform, key)) {
            if (SocialMediaPlatform[key as keyof typeof SocialMediaPlatform] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SocialMediaPlatformFromJSON(json: any): SocialMediaPlatform {
    return SocialMediaPlatformFromJSONTyped(json, false);
}

export function SocialMediaPlatformFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialMediaPlatform {
    return json as SocialMediaPlatform;
}

export function SocialMediaPlatformToJSON(value?: SocialMediaPlatform | null): any {
    return value as any;
}

export function SocialMediaPlatformToJSONTyped(value: any, ignoreDiscriminator: boolean): SocialMediaPlatform {
    return value as SocialMediaPlatform;
}

