/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguageCode } from './LanguageCode';
import {
    LanguageCodeFromJSON,
    LanguageCodeFromJSONTyped,
    LanguageCodeToJSON,
    LanguageCodeToJSONTyped,
} from './LanguageCode';
import type { SubtitleStyle } from './SubtitleStyle';
import {
    SubtitleStyleFromJSON,
    SubtitleStyleFromJSONTyped,
    SubtitleStyleToJSON,
    SubtitleStyleToJSONTyped,
} from './SubtitleStyle';
import type { SubtitleCapitalizationMethod } from './SubtitleCapitalizationMethod';
import {
    SubtitleCapitalizationMethodFromJSON,
    SubtitleCapitalizationMethodFromJSONTyped,
    SubtitleCapitalizationMethodToJSON,
    SubtitleCapitalizationMethodToJSONTyped,
} from './SubtitleCapitalizationMethod';
import type { SubtitlePosition } from './SubtitlePosition';
import {
    SubtitlePositionFromJSON,
    SubtitlePositionFromJSONTyped,
    SubtitlePositionToJSON,
    SubtitlePositionToJSONTyped,
} from './SubtitlePosition';

/**
 * 
 * @export
 * @interface SubtitleConfiguration
 */
export interface SubtitleConfiguration {
    /**
     * ID of the subtitle configuration.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    id?: string;
    /**
     * Kind of the subtitle configuration.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    kind?: string;
    /**
     * Name of the subtitle configuration.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    name?: string;
    /**
     * Name of the animation.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    animation?: string;
    /**
     * Color of the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    color?: string;
    /**
     * Size of the subtitles.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    size?: number;
    /**
     * Font of the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    font?: string;
    /**
     * Style of the subtitles, e.g., 'middle', 'bottom', 'top'.
     * @type {SubtitleStyle}
     * @memberof SubtitleConfiguration
     */
    subtitleStyle?: SubtitleStyle;
    /**
     * 
     * @type {SubtitleCapitalizationMethod}
     * @memberof SubtitleConfiguration
     */
    subtitleCapitalizationMethod?: SubtitleCapitalizationMethod;
    /**
     * 
     * @type {SubtitlePosition}
     * @memberof SubtitleConfiguration
     */
    subtitlePosition?: SubtitlePosition;
    /**
     * Background color for the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxFontColor?: string;
    /**
     * Transparency for the subtitles.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxTransparency?: number;
    /**
     * 
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxBackgroundColor?: string | null;
    /**
     * Color for the inactive part of the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    subtitleInactiveColor?: string;
    /**
     * Color for the active (highlighted) part of the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    subtitleActiveColor?: string;
    /**
     * Corner radius for the subtitles.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxCornerRadius?: number;
    /**
     * Compensation factor for word width.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxWidthCompensation?: number;
    /**
     * Border thickness for the subtitles.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    subtitleBoxBorderThickness?: number;
    /**
     * Font size for the subtitles.
     * @type {number}
     * @memberof SubtitleConfiguration
     */
    subtitleFontSize?: number;
    /**
     * Font name for the subtitles.
     * @type {string}
     * @memberof SubtitleConfiguration
     */
    subtitleFontName?: string;
    /**
     * Whether to use bold font for the subtitles.
     * @type {boolean}
     * @memberof SubtitleConfiguration
     */
    subtitleFontBold?: boolean;
    /**
     * Whether to use italic font for the subtitles.
     * @type {boolean}
     * @memberof SubtitleConfiguration
     */
    subtitleFontItalic?: boolean;
    /**
     * Whether to use underline font for the subtitles.
     * @type {boolean}
     * @memberof SubtitleConfiguration
     */
    subtitleFontUnderline?: boolean;
    /**
     * 
     * @type {LanguageCode}
     * @memberof SubtitleConfiguration
     */
    subtitleLanguageCode?: LanguageCode | null;
}



/**
 * Check if a given object implements the SubtitleConfiguration interface.
 */
export function instanceOfSubtitleConfiguration(value: object): value is SubtitleConfiguration {
    return true;
}

export function SubtitleConfigurationFromJSON(json: any): SubtitleConfiguration {
    return SubtitleConfigurationFromJSONTyped(json, false);
}

export function SubtitleConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubtitleConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'name': json['name'] == null ? undefined : json['name'],
        'animation': json['animation'] == null ? undefined : json['animation'],
        'color': json['color'] == null ? undefined : json['color'],
        'size': json['size'] == null ? undefined : json['size'],
        'font': json['font'] == null ? undefined : json['font'],
        'subtitleStyle': json['subtitle_style'] == null ? undefined : SubtitleStyleFromJSON(json['subtitle_style']),
        'subtitleCapitalizationMethod': json['subtitle_capitalization_method'] == null ? undefined : SubtitleCapitalizationMethodFromJSON(json['subtitle_capitalization_method']),
        'subtitlePosition': json['subtitle_position'] == null ? undefined : SubtitlePositionFromJSON(json['subtitle_position']),
        'subtitleBoxFontColor': json['subtitle_box_font_color'] == null ? undefined : json['subtitle_box_font_color'],
        'subtitleBoxTransparency': json['subtitle_box_transparency'] == null ? undefined : json['subtitle_box_transparency'],
        'subtitleBoxBackgroundColor': json['subtitle_box_background_color'] == null ? undefined : json['subtitle_box_background_color'],
        'subtitleInactiveColor': json['subtitle_inactive_color'] == null ? undefined : json['subtitle_inactive_color'],
        'subtitleActiveColor': json['subtitle_active_color'] == null ? undefined : json['subtitle_active_color'],
        'subtitleBoxCornerRadius': json['subtitle_box_corner_radius'] == null ? undefined : json['subtitle_box_corner_radius'],
        'subtitleBoxWidthCompensation': json['subtitle_box_width_compensation'] == null ? undefined : json['subtitle_box_width_compensation'],
        'subtitleBoxBorderThickness': json['subtitle_box_border_thickness'] == null ? undefined : json['subtitle_box_border_thickness'],
        'subtitleFontSize': json['subtitle_font_size'] == null ? undefined : json['subtitle_font_size'],
        'subtitleFontName': json['subtitle_font_name'] == null ? undefined : json['subtitle_font_name'],
        'subtitleFontBold': json['subtitle_font_bold'] == null ? undefined : json['subtitle_font_bold'],
        'subtitleFontItalic': json['subtitle_font_italic'] == null ? undefined : json['subtitle_font_italic'],
        'subtitleFontUnderline': json['subtitle_font_underline'] == null ? undefined : json['subtitle_font_underline'],
        'subtitleLanguageCode': json['subtitle_language_code'] == null ? undefined : LanguageCodeFromJSON(json['subtitle_language_code']),
    };
}

export function SubtitleConfigurationToJSON(json: any): SubtitleConfiguration {
    return SubtitleConfigurationToJSONTyped(json, false);
}

export function SubtitleConfigurationToJSONTyped(value?: SubtitleConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'name': value['name'],
        'animation': value['animation'],
        'color': value['color'],
        'size': value['size'],
        'font': value['font'],
        'subtitle_style': SubtitleStyleToJSON(value['subtitleStyle']),
        'subtitle_capitalization_method': SubtitleCapitalizationMethodToJSON(value['subtitleCapitalizationMethod']),
        'subtitle_position': SubtitlePositionToJSON(value['subtitlePosition']),
        'subtitle_box_font_color': value['subtitleBoxFontColor'],
        'subtitle_box_transparency': value['subtitleBoxTransparency'],
        'subtitle_box_background_color': value['subtitleBoxBackgroundColor'],
        'subtitle_inactive_color': value['subtitleInactiveColor'],
        'subtitle_active_color': value['subtitleActiveColor'],
        'subtitle_box_corner_radius': value['subtitleBoxCornerRadius'],
        'subtitle_box_width_compensation': value['subtitleBoxWidthCompensation'],
        'subtitle_box_border_thickness': value['subtitleBoxBorderThickness'],
        'subtitle_font_size': value['subtitleFontSize'],
        'subtitle_font_name': value['subtitleFontName'],
        'subtitle_font_bold': value['subtitleFontBold'],
        'subtitle_font_italic': value['subtitleFontItalic'],
        'subtitle_font_underline': value['subtitleFontUnderline'],
        'subtitle_language_code': LanguageCodeToJSON(value['subtitleLanguageCode']),
    };
}

