/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tags
 */
export interface Tags {
}

/**
 * Check if a given object implements the Tags interface.
 */
export function instanceOfTags(value: object): value is Tags {
    return true;
}

export function TagsFromJSON(json: any): Tags {
    return TagsFromJSONTyped(json, false);
}

export function TagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tags {
    return json;
}

export function TagsToJSON(json: any): Tags {
    return TagsToJSONTyped(json, false);
}

export function TagsToJSONTyped(value?: Tags | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

