/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrimConfiguration
 */
export interface TrimConfiguration {
    /**
     * ID of the trim configuration.
     * @type {string}
     * @memberof TrimConfiguration
     */
    id?: string;
    /**
     * Trim start in seconds.
     * @type {number}
     * @memberof TrimConfiguration
     */
    trimStartInSeconds?: number;
    /**
     * Trim end in seconds.
     * @type {number}
     * @memberof TrimConfiguration
     */
    trimEndInSeconds?: number;
}

/**
 * Check if a given object implements the TrimConfiguration interface.
 */
export function instanceOfTrimConfiguration(value: object): value is TrimConfiguration {
    return true;
}

export function TrimConfigurationFromJSON(json: any): TrimConfiguration {
    return TrimConfigurationFromJSONTyped(json, false);
}

export function TrimConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrimConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'trimStartInSeconds': json['trim_start_in_seconds'] == null ? undefined : json['trim_start_in_seconds'],
        'trimEndInSeconds': json['trim_end_in_seconds'] == null ? undefined : json['trim_end_in_seconds'],
    };
}

export function TrimConfigurationToJSON(json: any): TrimConfiguration {
    return TrimConfigurationToJSONTyped(json, false);
}

export function TrimConfigurationToJSONTyped(value?: TrimConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'trim_start_in_seconds': value['trimStartInSeconds'],
        'trim_end_in_seconds': value['trimEndInSeconds'],
    };
}

