/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrimConfiguration } from './TrimConfiguration';
import {
    TrimConfigurationFromJSON,
    TrimConfigurationFromJSONTyped,
    TrimConfigurationToJSON,
    TrimConfigurationToJSONTyped,
} from './TrimConfiguration';

/**
 * 
 * @export
 * @interface TrimApplication
 */
export interface TrimApplication {
    /**
     * 
     * @type {Array<TrimConfiguration>}
     * @memberof TrimApplication
     */
    trimConfigurations?: Array<TrimConfiguration>;
}

/**
 * Check if a given object implements the TrimApplication interface.
 */
export function instanceOfTrimApplication(value: object): value is TrimApplication {
    return true;
}

export function TrimApplicationFromJSON(json: any): TrimApplication {
    return TrimApplicationFromJSONTyped(json, false);
}

export function TrimApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrimApplication {
    if (json == null) {
        return json;
    }
    return {
        
        'trimConfigurations': json['trim_configurations'] == null ? undefined : ((json['trim_configurations'] as Array<any>).map(TrimConfigurationFromJSON)),
    };
}

export function TrimApplicationToJSON(json: any): TrimApplication {
    return TrimApplicationToJSONTyped(json, false);
}

export function TrimApplicationToJSONTyped(value?: TrimApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trim_configurations': value['trimConfigurations'] == null ? undefined : ((value['trimConfigurations'] as Array<any>).map(TrimConfigurationToJSON)),
    };
}

