/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatedAt
 */
export interface UpdatedAt {
}

/**
 * Check if a given object implements the UpdatedAt interface.
 */
export function instanceOfUpdatedAt(value: object): value is UpdatedAt {
    return true;
}

export function UpdatedAtFromJSON(json: any): UpdatedAt {
    return UpdatedAtFromJSONTyped(json, false);
}

export function UpdatedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedAt {
    return json;
}

export function UpdatedAtToJSON(json: any): UpdatedAt {
    return UpdatedAtToJSONTyped(json, false);
}

export function UpdatedAtToJSONTyped(value?: UpdatedAt | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

