/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConfirmSignup
 */
export interface UserConfirmSignup {
    /**
     * 
     * @type {string}
     * @memberof UserConfirmSignup
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserConfirmSignup
     */
    confirmationCode: string;
}

/**
 * Check if a given object implements the UserConfirmSignup interface.
 */
export function instanceOfUserConfirmSignup(value: object): value is UserConfirmSignup {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('confirmationCode' in value) || value['confirmationCode'] === undefined) return false;
    return true;
}

export function UserConfirmSignupFromJSON(json: any): UserConfirmSignup {
    return UserConfirmSignupFromJSONTyped(json, false);
}

export function UserConfirmSignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConfirmSignup {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'confirmationCode': json['confirmation_code'],
    };
}

export function UserConfirmSignupToJSON(json: any): UserConfirmSignup {
    return UserConfirmSignupToJSONTyped(json, false);
}

export function UserConfirmSignupToJSONTyped(value?: UserConfirmSignup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'confirmation_code': value['confirmationCode'],
    };
}

