/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
    RoleToJSONTyped,
} from './Role';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isSuperuser?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    subscriptionExpiresAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    subscriptionStatus?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    subscriptionCreatedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    subscriptionUpdatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    subscriptionPlan?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    subscriptionId?: string | null;
    /**
     * 
     * @type {Array<Role>}
     * @memberof User
     */
    roles?: Array<Role>;
    /**
     * 
     * @type {Array<Group>}
     * @memberof User
     */
    groups?: Array<Group>;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'id': json['id'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'isSuperuser': json['is_superuser'] == null ? undefined : json['is_superuser'],
        'name': json['name'],
        'subscriptionExpiresAt': json['subscription_expires_at'] == null ? undefined : (new Date(json['subscription_expires_at'])),
        'subscriptionStatus': json['subscription_status'] == null ? undefined : json['subscription_status'],
        'subscriptionCreatedAt': json['subscription_created_at'] == null ? undefined : (new Date(json['subscription_created_at'])),
        'subscriptionUpdatedAt': json['subscription_updated_at'] == null ? undefined : (new Date(json['subscription_updated_at'])),
        'subscriptionPlan': json['subscription_plan'] == null ? undefined : json['subscription_plan'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(RoleFromJSON)),
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(GroupFromJSON)),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'id': value['id'],
        'is_active': value['isActive'],
        'is_superuser': value['isSuperuser'],
        'name': value['name'],
        'subscription_expires_at': value['subscriptionExpiresAt'] == null ? undefined : ((value['subscriptionExpiresAt'] as any).toISOString()),
        'subscription_status': value['subscriptionStatus'],
        'subscription_created_at': value['subscriptionCreatedAt'] == null ? undefined : ((value['subscriptionCreatedAt'] as any).toISOString()),
        'subscription_updated_at': value['subscriptionUpdatedAt'] == null ? undefined : ((value['subscriptionUpdatedAt'] as any).toISOString()),
        'subscription_plan': value['subscriptionPlan'],
        'subscription_id': value['subscriptionId'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(RoleToJSON)),
        'groups': value['groups'] == null ? undefined : ((value['groups'] as Array<any>).map(GroupToJSON)),
    };
}

