/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDelete
 */
export interface UserDelete {
    /**
     * 
     * @type {string}
     * @memberof UserDelete
     */
    email: string;
}

/**
 * Check if a given object implements the UserDelete interface.
 */
export function instanceOfUserDelete(value: object): value is UserDelete {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserDeleteFromJSON(json: any): UserDelete {
    return UserDeleteFromJSONTyped(json, false);
}

export function UserDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDelete {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UserDeleteToJSON(json: any): UserDelete {
    return UserDeleteToJSONTyped(json, false);
}

export function UserDeleteToJSONTyped(value?: UserDelete | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

