/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Combined registration and confirmation in one request
 * @export
 * @interface UserRegisterAndConfirm
 */
export interface UserRegisterAndConfirm {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterAndConfirm
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterAndConfirm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterAndConfirm
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterAndConfirm
     */
    confirmationCode?: string | null;
}

/**
 * Check if a given object implements the UserRegisterAndConfirm interface.
 */
export function instanceOfUserRegisterAndConfirm(value: object): value is UserRegisterAndConfirm {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserRegisterAndConfirmFromJSON(json: any): UserRegisterAndConfirm {
    return UserRegisterAndConfirmFromJSONTyped(json, false);
}

export function UserRegisterAndConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterAndConfirm {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
        'confirmationCode': json['confirmation_code'] == null ? undefined : json['confirmation_code'],
    };
}

export function UserRegisterAndConfirmToJSON(json: any): UserRegisterAndConfirm {
    return UserRegisterAndConfirmToJSONTyped(json, false);
}

export function UserRegisterAndConfirmToJSONTyped(value?: UserRegisterAndConfirm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
        'confirmation_code': value['confirmationCode'],
    };
}

