/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoType = {
    Video: 'video',
    Image: 'image',
    Gif: 'gif'
} as const;
export type VideoType = typeof VideoType[keyof typeof VideoType];


export function instanceOfVideoType(value: any): boolean {
    for (const key in VideoType) {
        if (Object.prototype.hasOwnProperty.call(VideoType, key)) {
            if (VideoType[key as keyof typeof VideoType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoTypeFromJSON(json: any): VideoType {
    return VideoTypeFromJSONTyped(json, false);
}

export function VideoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoType {
    return json as VideoType;
}

export function VideoTypeToJSON(value?: VideoType | null): any {
    return value as any;
}

export function VideoTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoType {
    return value as VideoType;
}

