/* tslint:disable */
/* eslint-disable */
/**
 * Klippers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoPeopleContext = {
    Podcast: 'podcast',
    Solo: 'solo',
    Vlog: 'vlog',
    Interview: 'interview',
    Presentation: 'presentation'
} as const;
export type VideoPeopleContext = typeof VideoPeopleContext[keyof typeof VideoPeopleContext];


export function instanceOfVideoPeopleContext(value: any): boolean {
    for (const key in VideoPeopleContext) {
        if (Object.prototype.hasOwnProperty.call(VideoPeopleContext, key)) {
            if (VideoPeopleContext[key as keyof typeof VideoPeopleContext] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoPeopleContextFromJSON(json: any): VideoPeopleContext {
    return VideoPeopleContextFromJSONTyped(json, false);
}

export function VideoPeopleContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPeopleContext {
    return json as VideoPeopleContext;
}

export function VideoPeopleContextToJSON(value?: VideoPeopleContext | null): any {
    return value as any;
}

export function VideoPeopleContextToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoPeopleContext {
    return value as VideoPeopleContext;
}

