/* tslint:disable */
/* eslint-disable */
/**
 * Subtiter API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoFormat = {
    Mp4: 'mp4',
    Mov: 'mov',
    Avi: 'avi'
} as const;
export type VideoFormat = typeof VideoFormat[keyof typeof VideoFormat];


export function instanceOfVideoFormat(value: any): boolean {
    for (const key in VideoFormat) {
        if (Object.prototype.hasOwnProperty.call(VideoFormat, key)) {
            if (VideoFormat[key as keyof typeof VideoFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoFormatFromJSON(json: any): VideoFormat {
    return VideoFormatFromJSONTyped(json, false);
}

export function VideoFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoFormat {
    return json as VideoFormat;
}

export function VideoFormatToJSON(value?: VideoFormat | null): any {
    return value as any;
}

export function VideoFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoFormat {
    return value as VideoFormat;
}

