export enum EventType {
    UPDATE_SHORT_CONFIG = 'update-short-config',
    UPDATE_SHORT_CONFIG_SUBTITLE_POSITION = 'update-short-config-subtitle-position',
    UPDATE_SHORT_CONFIG_SUBTITLE_CAPITALIZATION_METHOD = 'update-short-config-subtitle-capitalization-method',
    UPDATE_SHORT_CONFIG_SUBTITLE_STYLE = 'update-short-config-subtitle-style',
    PAUSE_OTHER_VIDEOS = 'pause-other-videos',
    GENERATION_STARTED = 'generation-started',
    CLOSE_DIALOG_APPLICATION_SELECTION = 'close-dialog-application-selection',
    SHORT_SUBTITLE_STYLE_SELECTED = 'short-subtitle-style-selected',
    GENERATE_SHORTS_SET_ROUNDED_BOX_BG_COLOR = 'generate-shorts-set-rounded-box-bg-color',
    START_SHORTS_GENERATION = 'start-shorts-generation',
    SUBTITLE_CARD_TOGGLE = 'subtitle-card-toggle',
    SUBTITLING_SELECT_SUBTITLE_STYLE = 'subtitling-select-subtitle-style',
    SUBTITLE_DETAILS_UPDATE = 'subtitle-details-update',
    SUBTITLE_SELECTION_CHANGED = 'subtitle-selection-changed',
    SUBTITLING_CONFIG_CHANGED = 'subtitling-config-changed',
    REFRESH_VIDEO_LIST = 'refresh-video-list',
}
